/* 원자재 생산지 — 종목별 세계 8위 생산국 + 점유율 (큐레이션)
   출처: USGS(2023~24), EIA/IEA, FAO/USDA 등. 점유율은 근사치(생산국 기준). 검증·갱신 권장. */

const COMMODITIES = [
  { id: "copper-chile", commodity: "구리", type: "광물", site: "에스콘디다", country: "칠레", region: "안토파가스타", lat: -24.27, lng: -69.07, rank: 1, share: 24, stakes: [{ holder: "BHP", country: "호주", pct: 57.5 }, { holder: "Rio Tinto", country: "호주·영국", pct: 30 }], owners: "다국적 광산기업 + 국영 Codelco" },
  { id: "copper-drc", commodity: "구리", type: "광물", site: "카모아-카쿨라", country: "콩고민주공화국", region: "루알라바", lat: -10.73, lng: 25.38, rank: 2, share: 13, stakes: [{ holder: "Ivanhoe Mines", country: "캐나다", pct: 39.6 }, { holder: "Zijin Mining", country: "중국", pct: 39.6 }], owners: "중국 자본 깊이 관여" },
  { id: "copper-peru", commodity: "구리", type: "광물", site: "안타미나", country: "페루", region: "안카시", lat: -9.54, lng: -77.06, rank: 3, share: 12, stakes: [{ holder: "BHP", country: "호주", pct: 33.75 }, { holder: "Glencore", country: "스위스", pct: 33.75 }, { holder: "Teck", country: "캐나다", pct: 22.5 }], owners: "다국적 컨소시엄 소유" },
  { id: "copper-china", commodity: "구리", type: "광물", site: "더싱 동광", country: "중국", region: "장시성", lat: 28.95, lng: 117.59, rank: 4, share: 8, stakes: [{ holder: "Jiangxi Copper", country: "중국", pct: null }], owners: "국영기업 지배" },
  { id: "copper-usa", commodity: "구리", type: "광물", site: "모렌시", country: "미국", region: "애리조나", lat: 33.05, lng: -109.37, rank: 5, share: 5, stakes: [{ holder: "Freeport-McMoRan", country: "미국", pct: 72 }, { holder: "Sumitomo", country: "일본", pct: 28 }], owners: "미국 민간기업 주도" },
  { id: "copper-russia", commodity: "구리", type: "광물", site: "노릴스크", country: "러시아", region: "크라스노야르스크", lat: 69.35, lng: 88.2, rank: 6, share: 4, stakes: [{ holder: "Nornickel", country: "러시아", pct: null }], owners: "러시아 과두자본 지배" },
  { id: "copper-indonesia", commodity: "구리", type: "광물", site: "그라스버그", country: "인도네시아", region: "파푸아", lat: -4.05, lng: 137.12, rank: 7, share: 4, stakes: [{ holder: "Inalum(MIND ID)", country: "인도네시아", pct: 51 }, { holder: "Freeport-McMoRan", country: "미국", pct: 49 }], owners: "국영 지분 과반 + 미국 운영 — 2025.9 머드러시 사고(사망 7명)로 생산 중단, 2026 2분기 단계적 재가동(순위·점유율은 사고 전 기준)" },
  { id: "copper-australia", commodity: "구리", type: "광물", site: "올림픽댐", country: "호주", region: "사우스오스트레일리아", lat: -30.44, lng: 136.89, rank: 8, share: 4, stakes: [{ holder: "BHP", country: "호주", pct: 100 }], owners: "기관투자자 분산 소유" },

  { id: "ironore-australia", commodity: "철광석", type: "광물", site: "필바라(마운트 웨일백)", country: "호주", region: "웨스턴오스트레일리아", lat: -23.37, lng: 119.73, rank: 1, share: 35, stakes: [{ holder: "BHP", country: "호주", pct: null }, { holder: "Rio Tinto", country: "호주·영국", pct: null }, { holder: "Fortescue", country: "호주", pct: null }], owners: "다국적 광산기업 과점" },
  { id: "ironore-brazil", commodity: "철광석", type: "광물", site: "카라자스", country: "브라질", region: "파라", lat: -6.06, lng: -50.16, rank: 2, share: 17, stakes: [{ holder: "Vale", country: "브라질", pct: 100 }], owners: "기관투자자 분산 소유" },
  { id: "ironore-china", commodity: "철광석", type: "광물", site: "안산 철광", country: "중국", region: "랴오닝성", lat: 41.11, lng: 122.99, rank: 3, share: 14, stakes: [{ holder: "Ansteel", country: "중국", pct: null }], owners: "국영기업 지배" },
  { id: "ironore-india", commodity: "철광석", type: "광물", site: "바일라딜라", country: "인도", region: "차티스가르", lat: 18.72, lng: 81.23, rank: 4, share: 10, stakes: [{ holder: "NMDC", country: "인도", pct: null }], owners: "국영기업 지배" },
  { id: "ironore-russia", commodity: "철광석", type: "광물", site: "미하일로프스키", country: "러시아", region: "쿠르스크", lat: 52.33, lng: 35.37, rank: 5, share: 4, stakes: [{ holder: "Metalloinvest", country: "러시아", pct: null }], owners: "러시아 과두자본 지배" },
  { id: "ironore-iran", commodity: "철광석", type: "광물", site: "골에고하르", country: "이란", region: "케르만", lat: 29.1, lng: 55.32, rank: 6, share: 3, stakes: [{ holder: "GEG(국영계열)", country: "이란", pct: null }], owners: "국영·준국영 지배" },
  { id: "ironore-canada", commodity: "철광석", type: "광물", site: "몽라이트", country: "캐나다", region: "퀘벡", lat: 52.77, lng: -67.33, rank: 7, share: 3, stakes: [{ holder: "ArcelorMittal", country: "룩셈부르크", pct: null }], owners: "다국적 철강사 소유" },
  { id: "ironore-ukraine", commodity: "철광석", type: "광물", site: "크리비리흐", country: "우크라이나", region: "드니프로페트로우스크", lat: 47.91, lng: 33.39, rank: 8, share: 2, stakes: [{ holder: "Metinvest", country: "우크라이나", pct: null }], owners: "우크라이나 과두자본 소유" },

  { id: "gold-china", commodity: "금", type: "광물", site: "자오둥(산둥) 금광", country: "중국", region: "산둥성", lat: 37.45, lng: 120.35, rank: 1, share: 10, stakes: [{ holder: "Shandong Gold", country: "중국", pct: null }, { holder: "Zijin Mining", country: "중국", pct: null }], owners: "국영·민간 중국기업" },
  { id: "gold-australia", commodity: "금", type: "광물", site: "보딩턴", country: "호주", region: "웨스턴오스트레일리아", lat: -32.75, lng: 116.35, rank: 3, share: 9, stakes: [{ holder: "Newmont", country: "미국", pct: 100 }], owners: "미국 상장기업 소유" },
  { id: "gold-russia", commodity: "금", type: "광물", site: "올림피아다", country: "러시아", region: "크라스노야르스크", lat: 60.0, lng: 93.0, rank: 2, share: 9, stakes: [{ holder: "Polyus", country: "러시아", pct: null }], owners: "러시아 과두자본 지배" },
  { id: "gold-canada", commodity: "금", type: "광물", site: "캐나디안 말라틱", country: "캐나다", region: "퀘벡", lat: 48.13, lng: -78.13, rank: 4, share: 6, stakes: [{ holder: "Agnico Eagle", country: "캐나다", pct: 100 }], owners: "기관투자자 분산 소유" },
  { id: "gold-usa", commodity: "금", type: "광물", site: "칼린 트렌드(네바다)", country: "미국", region: "네바다", lat: 40.72, lng: -116.12, rank: 5, share: 5, stakes: [{ holder: "Barrick", country: "캐나다", pct: 61.5 }, { holder: "Newmont", country: "미국", pct: 38.5 }], owners: "다국적 합작 소유" },
  { id: "gold-kazakhstan", commodity: "금", type: "광물", site: "바실콥스코예", country: "카자흐스탄", region: "아크몰라", lat: 53.29, lng: 69.39, rank: 6, share: 4, stakes: [{ holder: "Altyntau(Glencore계)", country: "카자흐스탄·스위스", pct: null }], owners: "외국·현지 자본 혼재" },
  { id: "gold-mexico", commodity: "금", type: "광물", site: "페냐스키토", country: "멕시코", region: "사카테카스", lat: 24.65, lng: -101.7, rank: 7, share: 4, stakes: [{ holder: "Newmont", country: "미국", pct: 100 }], owners: "미국 상장기업 소유" },
  { id: "gold-indonesia", commodity: "금", type: "광물", site: "그라스버그", country: "인도네시아", region: "파푸아", lat: -4.05, lng: 137.12, rank: 8, share: 4, stakes: [{ holder: "Inalum(MIND ID)", country: "인도네시아", pct: 51 }, { holder: "Freeport-McMoRan", country: "미국", pct: 49 }], owners: "국영 지분 과반 + 미국 운영 — 2025.9 머드러시 사고(사망 7명)로 생산 중단, 2026 2분기 단계적 재가동(순위·점유율은 사고 전 기준)" },

  { id: "silver-mexico", commodity: "은", type: "광물", site: "프레스니요·사우시토", country: "멕시코", region: "사카테카스", lat: 23.18, lng: -102.87, rank: 1, share: 24, stakes: [{ holder: "Fresnillo plc", country: "멕시코·영국", pct: 100 }], owners: "멕시코 자본 + 런던 상장" },
  { id: "silver-china", commodity: "은", type: "광물", site: "은 부산물 광산(허난 등)", country: "중국", region: "허난성", lat: 34.0, lng: 111.2, rank: 2, share: 14, stakes: [{ holder: "중국 광산기업", country: "중국", pct: null }], owners: "국영·민간 중국기업" },
  { id: "silver-peru", commodity: "은", type: "광물", site: "안타미나", country: "페루", region: "안카시", lat: -9.54, lng: -77.06, rank: 3, share: 13, stakes: [{ holder: "BHP·Glencore·Teck", country: "호주·스위스·캐나다", pct: null }], owners: "다국적 컨소시엄 소유" },
  { id: "silver-chile", commodity: "은", type: "광물", site: "에스콘디다(부산물)", country: "칠레", region: "안토파가스타", lat: -24.27, lng: -69.07, rank: 4, share: 6, stakes: [{ holder: "BHP", country: "호주", pct: 57.5 }], owners: "다국적 광산기업 주도" },
  { id: "silver-poland", commodity: "은", type: "광물", site: "루빈(KGHM)", country: "폴란드", region: "하실레지아", lat: 51.4, lng: 16.2, rank: 5, share: 5, stakes: [{ holder: "KGHM", country: "폴란드", pct: null }], owners: "국영 지분 지배" },
  { id: "silver-australia", commodity: "은", type: "광물", site: "캐닝턴", country: "호주", region: "퀸즐랜드", lat: -21.86, lng: 140.91, rank: 6, share: 5, stakes: [{ holder: "South32", country: "호주", pct: 100 }], owners: "기관투자자 분산 소유" },
  { id: "silver-russia", commodity: "은", type: "광물", site: "두캇", country: "러시아", region: "마가단", lat: 62.57, lng: 155.37, rank: 7, share: 5, stakes: [{ holder: "Mangazeya Mining(구 Polymetal 러시아 사업)", country: "러시아", pct: null }], owners: "러시아 자본 지배 — 2024.3 Polymetal이 러시아 사업 Mangazeya에 매각" },
  { id: "silver-bolivia", commodity: "은", type: "광물", site: "산크리스토발", country: "볼리비아", region: "포토시", lat: -21.1, lng: -67.2, rank: 8, share: 5, stakes: [{ holder: "San Cristobal Mining Inc.", country: "미국", pct: 100 }], owners: "미국 자본 소유 — 2023.2 스미토모상사가 전량 매각" },

  { id: "lithium-australia", commodity: "리튬", type: "광물", site: "그린부시스", country: "호주", region: "웨스턴오스트레일리아", lat: -33.86, lng: 116.06, rank: 1, share: 37, stakes: [{ holder: "Albemarle", country: "미국", pct: 49 }, { holder: "Tianqi Lithium", country: "중국", pct: 26 }, { holder: "IGO", country: "호주", pct: 25 }], owners: "중국·미국·호주 합작" },
  { id: "lithium-chile", commodity: "리튬", type: "광물", site: "아타카마 염호", country: "칠레", region: "안토파가스타", lat: -23.5, lng: -68.35, rank: 2, share: 25, stakes: [{ holder: "SQM", country: "칠레", pct: null }, { holder: "Albemarle", country: "미국", pct: null }], owners: "국가 통제 강화 + 민간 운영" },
  { id: "lithium-china", commodity: "리튬", type: "광물", site: "이춘(장시) 리튬", country: "중국", region: "장시성", lat: 27.8, lng: 114.38, rank: 3, share: 14, stakes: [{ holder: "CATL", country: "중국", pct: null }, { holder: "Ganfeng Lithium", country: "중국", pct: null }], owners: "중국 민간·국영 혼재" },
  { id: "lithium-argentina", commodity: "리튬", type: "광물", site: "옴브레 무에르토 염호", country: "아르헨티나", region: "카타마르카", lat: -25.42, lng: -67.07, rank: 5, share: 7.5, stakes: [{ holder: "Rio Tinto(구 Arcadium/Livent)", country: "영국·호주", pct: null }, { holder: "POSCO", country: "한국", pct: null }], owners: "외국 자본 주도 개발" },
  { id: "lithium-brazil", commodity: "리튬", type: "광물", site: "미나스제라이스(미브라)", country: "브라질", region: "미나스제라이스", lat: -16.85, lng: -42.05, rank: 6, share: 4, stakes: [{ holder: "Sigma Lithium", country: "캐나다·브라질", pct: null }, { holder: "AMG", country: "네덜란드", pct: null }], owners: "외국 자본 주도" },
  { id: "lithium-zimbabwe", commodity: "리튬", type: "광물", site: "비키타", country: "짐바브웨", region: "마스빙고", lat: -20.08, lng: 31.57, rank: 4, share: 9, stakes: [{ holder: "Sinomine", country: "중국", pct: 100 }], owners: "중국 자본 깊이 관여" },
  { id: "lithium-portugal", commodity: "리튬", type: "광물", site: "바로주", country: "포르투갈", region: "노르트", lat: 41.7, lng: -7.7, rank: 7, share: 0.8, stakes: [{ holder: "Savannah Resources", country: "영국", pct: null }], owners: "외국 자본 개발 추진" },
  { id: "lithium-canada", commodity: "리튬", type: "광물", site: "노스아메리칸 리튬", country: "캐나다", region: "퀘벡", lat: 48.35, lng: -77.98, rank: 8, share: 0.6, stakes: [{ holder: "Elevra Lithium(구 Sayona·Piedmont, 2025.8 합병)", country: "호주·미국", pct: 100 }], owners: "외국 자본 소유 — 2사 합작 구조 소멸" },

  { id: "cobalt-drc", commodity: "코발트", type: "광물", site: "텡케 풍구루메", country: "콩고민주공화국", region: "루알라바", lat: -10.6, lng: 26.18, rank: 1, share: 74, stakes: [{ holder: "CMOC", country: "중국", pct: 80 }, { holder: "Gécamines", country: "콩고민주공화국", pct: 20 }], owners: "중국 자본 깊이 관여" },
  { id: "cobalt-indonesia", commodity: "코발트", type: "광물", site: "모로왈리(술라웨시)", country: "인도네시아", region: "술라웨시", lat: -2.7, lng: 122.0, rank: 2, share: 7, stakes: [{ holder: "중국계 HPAL 합작", country: "중국·인도네시아", pct: null }], owners: "중국 자본 깊이 관여" },
  { id: "cobalt-russia", commodity: "코발트", type: "광물", site: "노릴스크", country: "러시아", region: "크라스노야르스크", lat: 69.35, lng: 88.2, rank: 3, share: 4, stakes: [{ holder: "Nornickel", country: "러시아", pct: null }], owners: "러시아 과두자본 지배" },
  { id: "cobalt-australia", commodity: "코발트", type: "광물", site: "머린머린", country: "호주", region: "웨스턴오스트레일리아", lat: -28.76, lng: 121.88, rank: 4, share: 3, stakes: [{ holder: "Glencore", country: "스위스", pct: 100 }], owners: "다국적 광산기업 소유" },
  { id: "cobalt-canada", commodity: "코발트", type: "광물", site: "서드베리", country: "캐나다", region: "온타리오", lat: 46.49, lng: -81.0, rank: 5, share: 2, stakes: [{ holder: "Vale", country: "브라질", pct: null }, { holder: "Glencore", country: "스위스", pct: null }], owners: "다국적 광산기업 소유" },
  { id: "cobalt-philippines", commodity: "코발트", type: "광물", site: "수리가오", country: "필리핀", region: "카라가", lat: 9.8, lng: 125.5, rank: 6, share: 1.8, stakes: [{ holder: "Nickel Asia", country: "필리핀", pct: null }], owners: "현지 자본 + 일본 투자" },
  { id: "cobalt-cuba", commodity: "코발트", type: "광물", site: "모아", country: "쿠바", region: "올긴", lat: 20.66, lng: -74.95, rank: 7, share: 1.5, stakes: [{ holder: "Sherritt·국영 합작", country: "캐나다·쿠바", pct: null }], owners: "국영 + 외국 합작" },
  { id: "cobalt-madagascar", commodity: "코발트", type: "광물", site: "암바토비", country: "마다가스카르", region: "토아마시나", lat: -18.93, lng: 48.22, rank: 8, share: 1.5, stakes: [{ holder: "Sumitomo", country: "일본", pct: null }, { holder: "KORES", country: "한국", pct: null }], owners: "외국 자본 주도" },

  { id: "nickel-indonesia", commodity: "니켈", type: "광물", site: "소로아코(술라웨시)", country: "인도네시아", region: "술라웨시", lat: -2.53, lng: 121.36, rank: 1, share: 50, stakes: [{ holder: "Vale Indonesia", country: "브라질·인도네시아", pct: null }, { holder: "중국계 제련사", country: "중국", pct: null }], owners: "중국 자본 깊이 관여" },
  { id: "nickel-philippines", commodity: "니켈", type: "광물", site: "수리가오", country: "필리핀", region: "카라가", lat: 9.8, lng: 125.5, rank: 2, share: 11, stakes: [{ holder: "Nickel Asia", country: "필리핀", pct: null }], owners: "현지 자본 + 일본 투자" },
  { id: "nickel-russia", commodity: "니켈", type: "광물", site: "노릴스크", country: "러시아", region: "크라스노야르스크", lat: 69.35, lng: 88.2, rank: 3, share: 6, stakes: [{ holder: "Nornickel", country: "러시아", pct: null }], owners: "러시아 과두자본 지배" },
  { id: "nickel-newcaledonia", commodity: "니켈", type: "광물", site: "고로", country: "프랑스(뉴칼레도니아)", region: "뉴칼레도니아", lat: -22.28, lng: 166.98, rank: 4, share: 5, stakes: [{ holder: "Prony Resources", country: "뉴칼레도니아", pct: null }], owners: "현지·프랑스 자본" },
  { id: "nickel-australia", commodity: "니켈", type: "광물", site: "마운트 키스", country: "호주", region: "웨스턴오스트레일리아", lat: -27.25, lng: 120.55, rank: 5, share: 5, stakes: [{ holder: "BHP", country: "호주", pct: 100 }], owners: "기관투자자 분산 소유 — BHP Nickel West 전체 2024.10부터 케어&메인터넌스(가동 중단), 2027.2 재가동 여부 재검토(순위·점유율은 중단 전 기준)" },
  { id: "nickel-canada", commodity: "니켈", type: "광물", site: "서드베리", country: "캐나다", region: "온타리오", lat: 46.49, lng: -81.0, rank: 6, share: 5, stakes: [{ holder: "Vale", country: "브라질", pct: null }, { holder: "Glencore", country: "스위스", pct: null }], owners: "다국적 광산기업 소유" },
  { id: "nickel-china", commodity: "니켈", type: "광물", site: "진촨", country: "중국", region: "간쑤성", lat: 38.52, lng: 102.19, rank: 7, share: 3, stakes: [{ holder: "Jinchuan Group", country: "중국", pct: null }], owners: "국영기업 지배" },
  { id: "nickel-brazil", commodity: "니켈", type: "광물", site: "온사푸마", country: "브라질", region: "파라", lat: -6.55, lng: -51.1, rank: 8, share: 2, stakes: [{ holder: "Vale", country: "브라질", pct: 100 }], owners: "기관투자자 분산 소유" },

  { id: "ree-china", commodity: "희토류", type: "광물", site: "바이윈어보(바얀오보)", country: "중국", region: "네이멍구", lat: 41.77, lng: 109.97, rank: 1, share: 68, stakes: [{ holder: "China Northern Rare Earth", country: "중국", pct: null }], owners: "국영기업 지배" },
  { id: "ree-usa", commodity: "희토류", type: "광물", site: "마운틴패스", country: "미국", region: "캘리포니아", lat: 35.48, lng: -115.53, rank: 2, share: 12, stakes: [{ holder: "MP Materials", country: "미국", pct: 100 }], owners: "미국 상장기업 소유" },
  { id: "ree-myanmar", commodity: "희토류", type: "광물", site: "카친 채굴지", country: "미얀마", region: "카친", lat: 25.6, lng: 98.4, rank: 3, share: 11, stakes: [{ holder: "비공식 채굴(중국 유통)", country: "미얀마·중국", pct: null }], owners: "중국 자본 깊이 관여" },
  { id: "ree-australia", commodity: "희토류", type: "광물", site: "마운트웰드", country: "호주", region: "웨스턴오스트레일리아", lat: -28.86, lng: 122.55, rank: 4, share: 5, stakes: [{ holder: "Lynas Rare Earths", country: "호주", pct: 100 }], owners: "기관투자자 분산 소유" },
  { id: "ree-thailand", commodity: "희토류", type: "광물", site: "북부 채굴지", country: "태국", region: "북부", lat: 18.8, lng: 98.95, rank: 5, share: 2, stakes: [{ holder: "현지 광산기업", country: "태국", pct: null }], owners: "현지 자본" },
  { id: "ree-vietnam", commodity: "희토류", type: "광물", site: "동파오(라이쩌우)", country: "베트남", region: "라이쩌우", lat: 22.3, lng: 103.4, rank: 6, share: 1.5, stakes: [{ holder: "국영·합작", country: "베트남", pct: null }], owners: "국영 + 외국 합작" },
  { id: "ree-india", commodity: "희토류", type: "광물", site: "케랄라 모나자이트", country: "인도", region: "케랄라 연안", lat: 8.48, lng: 76.92, rank: 7, share: 1, stakes: [{ holder: "IREL", country: "인도", pct: null }], owners: "국영기업 지배" },
  { id: "ree-russia", commodity: "희토류", type: "광물", site: "로보제로", country: "러시아", region: "무르만스크", lat: 67.9, lng: 34.9, rank: 8, share: 1, stakes: [{ holder: "러시아 국영계열", country: "러시아", pct: null }], owners: "국영·준국영 지배" },

  { id: "uranium-kazakhstan", commodity: "우라늄", type: "에너지", site: "인카이·토르트쿠두크", country: "카자흐스탄", region: "투르키스탄", lat: 45.35, lng: 67.1, rank: 1, share: 43, stakes: [{ holder: "Kazatomprom", country: "카자흐스탄", pct: null }], owners: "국영기업 지배" },
  { id: "uranium-canada", commodity: "우라늄", type: "에너지", site: "시가레이크", country: "캐나다", region: "서스캐처원", lat: 58.07, lng: -104.53, rank: 2, share: 15, stakes: [{ holder: "Cameco", country: "캐나다", pct: 57.4 }, { holder: "Orano", country: "프랑스", pct: 42.6 }], owners: "다국적 합작 소유" },
  { id: "uranium-namibia", commodity: "우라늄", type: "에너지", site: "후사브", country: "나미비아", region: "에롱고", lat: -22.63, lng: 15.02, rank: 3, share: 11, stakes: [{ holder: "CGN(중국광핵)", country: "중국", pct: null }], owners: "중국 자본 깊이 관여" },
  { id: "uranium-australia", commodity: "우라늄", type: "에너지", site: "올림픽댐", country: "호주", region: "사우스오스트레일리아", lat: -30.44, lng: 136.89, rank: 4, share: 9, stakes: [{ holder: "BHP", country: "호주", pct: 100 }], owners: "기관투자자 분산 소유" },
  { id: "uranium-uzbekistan", commodity: "우라늄", type: "에너지", site: "나보이", country: "우즈베키스탄", region: "나보이", lat: 40.1, lng: 65.4, rank: 5, share: 7, stakes: [{ holder: "Navoiyuran", country: "우즈베키스탄", pct: null }], owners: "국영기업 지배" },
  { id: "uranium-russia", commodity: "우라늄", type: "에너지", site: "프리아르군스키", country: "러시아", region: "자바이칼", lat: 50.09, lng: 118.04, rank: 6, share: 5, stakes: [{ holder: "ARMZ(Rosatom)", country: "러시아", pct: null }], owners: "국영기업 지배" },
  { id: "uranium-niger", commodity: "우라늄", type: "에너지", site: "아를리트(소마이르)", country: "니제르", region: "아가데즈", lat: 18.74, lng: 7.39, rank: 7, share: 4, stakes: [{ holder: "니제르 정부(국유화 선언, 분쟁 중)", country: "니제르", pct: null }], owners: "니제르 군정 2025.6 국유화 선언 — 구 Orano 63.4%+Sopamin 36.6%, 2024.12 Orano 운영권 상실·ICSID 중재 진행, 2024년 말 수출 봉쇄로 조업 중단" },
  { id: "uranium-china", commodity: "우라늄", type: "에너지", site: "신장 채굴지", country: "중국", region: "신장", lat: 41.0, lng: 86.0, rank: 8, share: 3, stakes: [{ holder: "CNNC", country: "중국", pct: null }], owners: "국영기업 지배" },

  { id: "bauxite-australia", commodity: "보크사이트", type: "광물", site: "웨이파", country: "호주", region: "퀸즐랜드", lat: -12.65, lng: 141.85, rank: 2, share: 22, stakes: [{ holder: "Rio Tinto", country: "호주·영국", pct: 100 }], owners: "다국적 광산기업 소유" },
  { id: "bauxite-guinea", commodity: "보크사이트", type: "광물", site: "보케(CBG)", country: "기니", region: "보케", lat: 10.94, lng: -14.3, rank: 1, share: 29, stakes: [{ holder: "CBG(Halco)", country: "미국·호주·기니", pct: 51 }, { holder: "기니 정부", country: "기니", pct: 49 }], owners: "다국적 합작 + 중국 투자 확대" },
  { id: "bauxite-china", commodity: "보크사이트", type: "광물", site: "산시성 채굴지", country: "중국", region: "산시성", lat: 37.5, lng: 112.0, rank: 3, share: 18, stakes: [{ holder: "Chinalco", country: "중국", pct: null }], owners: "국영기업 지배" },
  { id: "bauxite-brazil", commodity: "보크사이트", type: "광물", site: "트롬베타스·주루치", country: "브라질", region: "파라", lat: -1.46, lng: -56.38, rank: 4, share: 8, stakes: [{ holder: "Mineração Rio do Norte", country: "브라질", pct: null }, { holder: "Alcoa", country: "미국", pct: null }], owners: "현지·다국적 합작" },
  { id: "bauxite-india", commodity: "보크사이트", type: "광물", site: "오디샤 채굴지", country: "인도", region: "오디샤", lat: 19.0, lng: 83.0, rank: 5, share: 6, stakes: [{ holder: "NALCO", country: "인도", pct: null }], owners: "국영기업 지배" },
  { id: "bauxite-indonesia", commodity: "보크사이트", type: "광물", site: "빈탄(리아우)", country: "인도네시아", region: "리아우제도", lat: 1.0, lng: 104.5, rank: 6, share: 5, stakes: [{ holder: "Antam(MIND ID)", country: "인도네시아", pct: null }], owners: "국영기업 지배" },
  { id: "bauxite-jamaica", commodity: "보크사이트", type: "광물", site: "자메이카 채굴지", country: "자메이카", region: "매닝빌", lat: 18.15, lng: -77.35, rank: 7, share: 2, stakes: [{ holder: "외국 알루미나사", country: "미국·중국·러시아", pct: null }], owners: "외국 자본 + 국영 지분" },
  { id: "bauxite-russia", commodity: "보크사이트", type: "광물", site: "북우랄 보크사이트", country: "러시아", region: "스베르들롭스크", lat: 60.15, lng: 59.96, rank: 8, share: 1.5, stakes: [{ holder: "Rusal", country: "러시아", pct: null }], owners: "러시아 과두자본 지배" },

  { id: "pgm-southafrica", commodity: "백금족", type: "광물", site: "부시벨드(모갈락웨나)", country: "남아프리카공화국", region: "림포포", lat: -23.98, lng: 28.92, rank: 1, share: 70, stakes: [{ holder: "Anglo American Platinum", country: "남아공·영국", pct: null }], owners: "다국적 광산기업 주도" },
  { id: "pgm-russia", commodity: "백금족", type: "광물", site: "노릴스크", country: "러시아", region: "크라스노야르스크", lat: 69.35, lng: 88.2, rank: 2, share: 11, stakes: [{ holder: "Nornickel", country: "러시아", pct: null }], owners: "러시아 과두자본 지배" },
  { id: "pgm-zimbabwe", commodity: "백금족", type: "광물", site: "그레이트다이크(짐플라츠)", country: "짐바브웨", region: "마쇼날랜드", lat: -18.7, lng: 30.4, rank: 3, share: 8, stakes: [{ holder: "Implats(Zimplats)", country: "남아공", pct: null }], owners: "남아공 자본 주도" },
  { id: "pgm-canada", commodity: "백금족", type: "광물", site: "락데질(썬더베이 인근)", country: "캐나다", region: "온타리오(썬더베이 인근)", lat: 49.17, lng: -89.61, rank: 4, share: 3, stakes: [{ holder: "Impala Canada", country: "남아공", pct: null }], owners: "외국 자본 소유" },
  { id: "pgm-usa", commodity: "백금족", type: "광물", site: "스틸워터", country: "미국", region: "몬태나", lat: 45.38, lng: -109.88, rank: 5, share: 3, stakes: [{ holder: "Sibanye-Stillwater", country: "남아공", pct: 100 }], owners: "남아공 자본 소유" },
  { id: "pgm-china", commodity: "백금족", type: "광물", site: "진촨(부산물)", country: "중국", region: "간쑤성", lat: 38.52, lng: 102.19, rank: 6, share: 1.5, stakes: [{ holder: "Jinchuan Group", country: "중국", pct: null }], owners: "국영기업 지배" },
  { id: "pgm-finland", commodity: "백금족", type: "광물", site: "케비차", country: "핀란드", region: "라플란드", lat: 67.7, lng: 26.95, rank: 7, share: 1, stakes: [{ holder: "Boliden", country: "스웨덴", pct: 100 }], owners: "북유럽 자본 소유" },
  { id: "pgm-colombia", commodity: "백금족", type: "광물", site: "초코 사금지", country: "콜롬비아", region: "초코", lat: 5.3, lng: -76.6, rank: 8, share: 1, stakes: [{ holder: "소규모·수공 채굴", country: "콜롬비아", pct: null }], owners: "현지 소규모 채굴" },

  { id: "oil-usa", commodity: "원유", type: "에너지", site: "퍼미언 분지", country: "미국", region: "텍사스", lat: 31.85, lng: -102.1, rank: 1, share: 20, stakes: [{ holder: "ExxonMobil", country: "미국", pct: null }, { holder: "Chevron", country: "미국", pct: null }], owners: "민간 메이저 + 독립계 분산" },
  { id: "oil-saudi", commodity: "원유", type: "에너지", site: "가와르", country: "사우디아라비아", region: "동부주", lat: 25.4, lng: 49.6, rank: 2, share: 11, stakes: [{ holder: "Saudi Aramco", country: "사우디아라비아", pct: null }], owners: "국영기업 지배" },
  { id: "oil-russia", commodity: "원유", type: "에너지", site: "프리옵스코예", country: "러시아", region: "한티만시", lat: 61.25, lng: 70.15, rank: 3, share: 11, stakes: [{ holder: "Rosneft", country: "러시아", pct: null }], owners: "국영기업 지배" },
  { id: "oil-canada", commodity: "원유", type: "에너지", site: "애서배스카 오일샌드", country: "캐나다", region: "앨버타", lat: 56.73, lng: -111.38, rank: 4, share: 6, stakes: [{ holder: "Suncor", country: "캐나다", pct: null }, { holder: "CNRL", country: "캐나다", pct: null }], owners: "캐나다 민간기업 주도" },
  { id: "oil-iraq", commodity: "원유", type: "에너지", site: "루마일라", country: "이라크", region: "바스라", lat: 30.15, lng: 47.4, rank: 5, share: 5, stakes: [{ holder: "BP", country: "영국", pct: null }, { holder: "PetroChina", country: "중국", pct: null }, { holder: "Basra Oil", country: "이라크", pct: null }], owners: "국영 주도 + 외국 서비스계약" },
  { id: "oil-china", commodity: "원유", type: "에너지", site: "다칭 유전", country: "중국", region: "헤이룽장성", lat: 46.58, lng: 125.03, rank: 6, share: 5, stakes: [{ holder: "PetroChina(CNPC)", country: "중국", pct: null }], owners: "국영기업 지배" },
  { id: "oil-uae", commodity: "원유", type: "에너지", site: "어퍼자쿰", country: "아랍에미리트", region: "아부다비 해상(페르시아만)", lat: 24.87, lng: 53.65, rank: 7, share: 4, stakes: [{ holder: "ADNOC", country: "아랍에미리트", pct: null }], owners: "국영기업 지배" },
  { id: "oil-brazil", commodity: "원유", type: "에너지", site: "투피(룰라) 유전", country: "브라질", region: "산투스 분지 해상", lat: -25.0, lng: -43.2, rank: 8, share: 4, stakes: [{ holder: "Petrobras", country: "브라질", pct: null }], owners: "국영기업 지배" },

  { id: "gas-usa", commodity: "천연가스", type: "에너지", site: "마셀러스(애팔래치아)", country: "미국", region: "펜실베이니아(마셀러스)", lat: 40.3, lng: -79.5, rank: 1, share: 24, stakes: [{ holder: "EQT", country: "미국", pct: null }, { holder: "독립계 생산사", country: "미국", pct: null }], owners: "민간기업 분산 소유" },
  { id: "gas-russia", commodity: "천연가스", type: "에너지", site: "우렌고이·야말", country: "러시아", region: "야말로네네츠", lat: 65.99, lng: 76.93, rank: 2, share: 15, stakes: [{ holder: "Gazprom", country: "러시아", pct: null }], owners: "국영기업 지배" },
  { id: "gas-iran", commodity: "천연가스", type: "에너지", site: "사우스파스", country: "이란", region: "페르시아만 해상(부셰르 남쪽)", lat: 26.6, lng: 52.2, rank: 3, share: 6, stakes: [{ holder: "NIOC", country: "이란", pct: null }], owners: "국영기업 지배" },
  { id: "gas-china", commodity: "천연가스", type: "에너지", site: "쓰촨·타림 분지", country: "중국", region: "쓰촨 분지", lat: 30.6, lng: 104.8, rank: 4, share: 6, stakes: [{ holder: "PetroChina", country: "중국", pct: null }], owners: "국영기업 지배" },
  { id: "gas-canada", commodity: "천연가스", type: "에너지", site: "몬트니", country: "캐나다", region: "브리티시컬럼비아", lat: 56.8, lng: -121.2, rank: 5, share: 4, stakes: [{ holder: "캐나다 민간 생산사", country: "캐나다", pct: null }], owners: "민간기업 분산 소유" },
  { id: "gas-qatar", commodity: "천연가스", type: "에너지", site: "노스필드", country: "카타르", region: "페르시아만 해상(카타르 북동)", lat: 26.5, lng: 52.0, rank: 6, share: 4, stakes: [{ holder: "QatarEnergy", country: "카타르", pct: null }], owners: "국영기업 지배" },
  { id: "gas-australia", commodity: "천연가스", type: "에너지", site: "노스웨스트셸프·고곤", country: "호주", region: "인도양 해상(NWS·노스랭킨)", lat: -19.58, lng: 116.13, rank: 7, share: 4, stakes: [{ holder: "Woodside", country: "호주", pct: null }, { holder: "Chevron", country: "미국", pct: null }], owners: "다국적 컨소시엄 소유" },
  { id: "gas-norway", commodity: "천연가스", type: "에너지", site: "트롤", country: "노르웨이", region: "북해 해상", lat: 60.65, lng: 3.73, rank: 8, share: 3, stakes: [{ holder: "Equinor", country: "노르웨이", pct: null }], owners: "국가 지분 지배" },

  { id: "coal-china", commodity: "석탄", type: "에너지", site: "산시성(다퉁)", country: "중국", region: "산시성", lat: 40.08, lng: 113.3, rank: 1, share: 50, stakes: [{ holder: "China Energy(Shenhua)", country: "중국", pct: null }], owners: "국영기업 지배" },
  { id: "coal-india", commodity: "석탄", type: "에너지", site: "자리아·탈처", country: "인도", region: "자르칸드", lat: 23.75, lng: 86.4, rank: 2, share: 10, stakes: [{ holder: "Coal India", country: "인도", pct: null }], owners: "국영기업 지배" },
  { id: "coal-indonesia", commodity: "석탄", type: "에너지", site: "동칼리만탄", country: "인도네시아", region: "동칼리만탄", lat: -1.5, lng: 115.0, rank: 3, share: 8, stakes: [{ holder: "Adaro", country: "인도네시아", pct: null }, { holder: "Bumi Resources", country: "인도네시아", pct: null }], owners: "현지 대기업 소유" },
  { id: "coal-usa", commodity: "석탄", type: "에너지", site: "파우더리버 분지", country: "미국", region: "와이오밍", lat: 44.0, lng: -105.5, rank: 4, share: 6, stakes: [{ holder: "Peabody Energy", country: "미국", pct: null }, { holder: "Core Natural Resources(구 Arch, 2025.1 CONSOL과 합병)", country: "미국", pct: null }], owners: "민간기업 소유" },
  { id: "coal-australia", commodity: "석탄", type: "에너지", site: "보엔 분지", country: "호주", region: "퀸즐랜드", lat: -22.5, lng: 148.0, rank: 5, share: 5, stakes: [{ holder: "BHP", country: "호주", pct: null }, { holder: "Glencore", country: "스위스", pct: null }], owners: "다국적 광산기업 주도" },
  { id: "coal-russia", commodity: "석탄", type: "에너지", site: "쿠즈바스", country: "러시아", region: "케메로보", lat: 54.0, lng: 87.0, rank: 6, share: 5, stakes: [{ holder: "SUEK", country: "러시아", pct: null }], owners: "러시아 과두자본 지배" },
  { id: "coal-southafrica", commodity: "석탄", type: "에너지", site: "비트뱅크(하이벨드)", country: "남아프리카공화국", region: "음푸말랑가", lat: -25.87, lng: 29.2, rank: 7, share: 3, stakes: [{ holder: "Exxaro·Thungela 등", country: "남아공", pct: null }], owners: "현지 자본 주도" },
  { id: "coal-kazakhstan", commodity: "석탄", type: "에너지", site: "에키바스투스", country: "카자흐스탄", region: "파블로다르", lat: 51.73, lng: 75.32, rank: 8, share: 1.5, stakes: [{ holder: "Bogatyr Komir", country: "카자흐스탄", pct: null }], owners: "국영·현지 자본" },

  { id: "soybean-brazil", commodity: "대두", type: "농산물", site: "마투그로수", country: "브라질", region: "마투그로수", lat: -12.6, lng: -55.7, rank: 1, share: 40, stakes: [{ holder: "대규모 영농기업·농가", country: "브라질", pct: null }], owners: "현지 영농기업 + 곡물메이저 유통" },
  { id: "soybean-usa", commodity: "대두", type: "농산물", site: "아이오와·일리노이", country: "미국", region: "아이오와", lat: 42.0, lng: -93.5, rank: 2, share: 28, stakes: [{ holder: "가족농·영농기업", country: "미국", pct: null }], owners: "민간 농가 + 곡물메이저 유통" },
  { id: "soybean-argentina", commodity: "대두", type: "농산물", site: "팜파스", country: "아르헨티나", region: "산타페", lat: -33.0, lng: -62.0, rank: 3, share: 12, stakes: [{ holder: "영농기업·농가", country: "아르헨티나", pct: null }], owners: "현지 농가 + 곡물메이저 유통" },
  { id: "soybean-china", commodity: "대두", type: "농산물", site: "헤이룽장성", country: "중국", region: "헤이룽장성", lat: 47.0, lng: 127.0, rank: 4, share: 5, stakes: [{ holder: "국영농장·농가", country: "중국", pct: null }], owners: "국영농장 + 소농" },
  { id: "soybean-india", commodity: "대두", type: "농산물", site: "마디아프라데시", country: "인도", region: "마디아프라데시", lat: 23.0, lng: 77.5, rank: 5, share: 3, stakes: [{ holder: "소규모 농가", country: "인도", pct: null }], owners: "소농 분산 소유" },
  { id: "soybean-paraguay", commodity: "대두", type: "농산물", site: "알토파라나", country: "파라과이", region: "알토파라나", lat: -25.5, lng: -55.0, rank: 6, share: 3, stakes: [{ holder: "영농기업·농가", country: "파라과이", pct: null }], owners: "현지·외국 영농기업" },
  { id: "soybean-canada", commodity: "대두", type: "농산물", site: "온타리오·매니토바", country: "캐나다", region: "온타리오", lat: 43.5, lng: -80.5, rank: 7, share: 2, stakes: [{ holder: "가족농", country: "캐나다", pct: null }], owners: "민간 농가" },
  { id: "soybean-russia", commodity: "대두", type: "농산물", site: "아무르주", country: "러시아", region: "아무르", lat: 50.3, lng: 127.5, rank: 8, share: 2, stakes: [{ holder: "영농기업", country: "러시아", pct: null }], owners: "현지 영농기업" },

  { id: "wheat-china", commodity: "밀", type: "농산물", site: "화베이평원(허난)", country: "중국", region: "허난성", lat: 34.5, lng: 113.5, rank: 1, share: 17, stakes: [{ holder: "농가·국영조달", country: "중국", pct: null }], owners: "소농 + 국가 조달" },
  { id: "wheat-india", commodity: "밀", type: "농산물", site: "펀자브", country: "인도", region: "펀자브", lat: 30.9, lng: 75.8, rank: 2, share: 14, stakes: [{ holder: "소규모 농가", country: "인도", pct: null }], owners: "소농 + 국가 조달" },
  { id: "wheat-russia", commodity: "밀", type: "농산물", site: "크라스노다르·로스토프", country: "러시아", region: "남부 러시아", lat: 46.0, lng: 40.0, rank: 3, share: 11, stakes: [{ holder: "대형 영농기업", country: "러시아", pct: null }], owners: "현지 영농기업 + 국가 수출통제" },
  { id: "wheat-usa", commodity: "밀", type: "농산물", site: "캔자스(대평원)", country: "미국", region: "캔자스", lat: 38.5, lng: -98.0, rank: 4, share: 6, stakes: [{ holder: "가족농·영농기업", country: "미국", pct: null }], owners: "민간 농가 + 곡물메이저 유통" },
  { id: "wheat-canada", commodity: "밀", type: "농산물", site: "서스캐처원", country: "캐나다", region: "서스캐처원", lat: 52.0, lng: -106.0, rank: 5, share: 4, stakes: [{ holder: "가족농", country: "캐나다", pct: null }], owners: "민간 농가" },
  { id: "wheat-france", commodity: "밀", type: "농산물", site: "보스 평원", country: "프랑스", region: "상트르발드루아르", lat: 48.2, lng: 1.7, rank: 6, share: 4, stakes: [{ holder: "영농기업·협동조합", country: "프랑스", pct: null }], owners: "농가 + 협동조합" },
  { id: "wheat-australia", commodity: "밀", type: "농산물", site: "뉴사우스웨일스 곡창", country: "호주", region: "뉴사우스웨일스", lat: -31.0, lng: 147.0, rank: 7, share: 4, stakes: [{ holder: "대규모 농가", country: "호주", pct: null }], owners: "민간 농가" },
  { id: "wheat-pakistan", commodity: "밀", type: "농산물", site: "펀자브", country: "파키스탄", region: "펀자브", lat: 31.1, lng: 72.7, rank: 8, share: 3, stakes: [{ holder: "소규모 농가", country: "파키스탄", pct: null }], owners: "소농 + 국가 조달" },

  { id: "corn-usa", commodity: "옥수수", type: "농산물", site: "아이오와(콘벨트)", country: "미국", region: "아이오와", lat: 42.0, lng: -93.5, rank: 1, share: 32, stakes: [{ holder: "가족농·영농기업", country: "미국", pct: null }], owners: "민간 농가 + 곡물메이저 유통" },
  { id: "corn-china", commodity: "옥수수", type: "농산물", site: "동북(지린)", country: "중국", region: "지린성", lat: 43.8, lng: 125.3, rank: 2, share: 23, stakes: [{ holder: "농가·국영조달", country: "중국", pct: null }], owners: "소농 + 국가 조달" },
  { id: "corn-brazil", commodity: "옥수수", type: "농산물", site: "마투그로수(2기작)", country: "브라질", region: "마투그로수", lat: -12.6, lng: -55.7, rank: 3, share: 10, stakes: [{ holder: "대규모 영농기업", country: "브라질", pct: null }], owners: "현지 영농기업 + 곡물메이저 유통" },
  { id: "corn-argentina", commodity: "옥수수", type: "농산물", site: "코르도바", country: "아르헨티나", region: "코르도바", lat: -32.0, lng: -63.5, rank: 4, share: 4, stakes: [{ holder: "영농기업·농가", country: "아르헨티나", pct: null }], owners: "현지 농가 + 곡물메이저 유통" },
  { id: "corn-india", commodity: "옥수수", type: "농산물", site: "카르나타카", country: "인도", region: "카르나타카", lat: 15.3, lng: 75.7, rank: 5, share: 3, stakes: [{ holder: "소규모 농가", country: "인도", pct: null }], owners: "소농 분산 소유" },
  { id: "corn-mexico", commodity: "옥수수", type: "농산물", site: "시날로아", country: "멕시코", region: "시날로아", lat: 25.0, lng: -107.5, rank: 6, share: 2.5, stakes: [{ holder: "농가·영농기업", country: "멕시코", pct: null }], owners: "농가 분산 소유" },
  { id: "corn-ukraine", commodity: "옥수수", type: "농산물", site: "폴타바", country: "우크라이나", region: "폴타바", lat: 49.6, lng: 34.5, rank: 7, share: 2.5, stakes: [{ holder: "대형 영농기업", country: "우크라이나", pct: null }], owners: "현지 영농기업 + 수출 유통" },
  { id: "corn-indonesia", commodity: "옥수수", type: "농산물", site: "동자바", country: "인도네시아", region: "동자바", lat: -7.5, lng: 112.0, rank: 8, share: 2, stakes: [{ holder: "소규모 농가", country: "인도네시아", pct: null }], owners: "소농 분산 소유" },

  { id: "palmoil-indonesia", commodity: "팜유", type: "농산물", site: "리아우(수마트라)", country: "인도네시아", region: "리아우", lat: 0.5, lng: 101.4, rank: 1, share: 59, stakes: [{ holder: "대형 플랜테이션 기업", country: "인도네시아", pct: null }], owners: "대기업 + 소농 혼재" },
  { id: "palmoil-malaysia", commodity: "팜유", type: "농산물", site: "사바", country: "말레이시아", region: "사바", lat: 5.4, lng: 117.0, rank: 2, share: 24, stakes: [{ holder: "SD Guthrie(구 Sime Darby Plantation) 등", country: "말레이시아", pct: null }], owners: "대형 플랜테이션 기업" },
  { id: "palmoil-thailand", commodity: "팜유", type: "농산물", site: "수랏타니", country: "태국", region: "수랏타니", lat: 8.5, lng: 99.0, rank: 3, share: 4, stakes: [{ holder: "소규모 농가·기업", country: "태국", pct: null }], owners: "소농 + 가공기업" },
  { id: "palmoil-colombia", commodity: "팜유", type: "농산물", site: "메타", country: "콜롬비아", region: "메타", lat: 3.5, lng: -73.0, rank: 4, share: 2, stakes: [{ holder: "플랜테이션 기업·농가", country: "콜롬비아", pct: null }], owners: "현지 기업 + 농가" },
  { id: "palmoil-nigeria", commodity: "팜유", type: "농산물", site: "아콰이봄", country: "나이지리아", region: "아콰이봄", lat: 5.0, lng: 7.9, rank: 5, share: 2, stakes: [{ holder: "소규모 농가·기업", country: "나이지리아", pct: null }], owners: "소농 + 기업 혼재" },
  { id: "palmoil-guatemala", commodity: "팜유", type: "농산물", site: "이사발 저지대", country: "과테말라", region: "이사발", lat: 15.7, lng: -89.0, rank: 6, share: 1.2, stakes: [{ holder: "플랜테이션 기업", country: "과테말라", pct: null }], owners: "대형 플랜테이션 기업" },
  { id: "palmoil-honduras", commodity: "팜유", type: "농산물", site: "북부 해안 저지대", country: "온두라스", region: "아틀란티다", lat: 15.5, lng: -87.0, rank: 7, share: 0.8, stakes: [{ holder: "협동조합·기업", country: "온두라스", pct: null }], owners: "협동조합 + 기업" },
  { id: "palmoil-png", commodity: "팜유", type: "농산물", site: "웨스트뉴브리튼", country: "파푸아뉴기니", region: "웨스트뉴브리튼", lat: -5.5, lng: 150.5, rank: 8, share: 0.8, stakes: [{ holder: "New Britain Palm Oil(SD Guthrie 자회사)", country: "말레이시아", pct: null }], owners: "말레이시아 SD Guthrie(구 Sime Darby Plantation)가 2015.3 인수한 대형 플랜테이션 기업" },

  // ==== top-10 확장 (9·10위, 2025 조사: USGS MCS 2025/26·WNA·EI·USDA) ====
  { id: "copper-kazakhstan", commodity: "구리", type: "광물", site: "악토가이 광산", country: "카자흐스탄", region: "아바이주(동카자흐스탄)", lat: 46.97, lng: 79.75, rank: 9, share: 3, stakes: [{ holder: "KAZ 미네랄스", country: "카자흐스탄", pct: 100 }], owners: "카자흐 민간 KAZ 미네랄스 소유 — 생산 구리 대부분 중국으로 수출" },
  { id: "copper-mexico", commodity: "구리", type: "광물", site: "부에나비스타 광산", country: "멕시코", region: "소노라", lat: 30.98, lng: -110.3, rank: 10, share: 3, stakes: [{ holder: "Grupo México", country: "멕시코", pct: 100 }], owners: "멕시코 재벌 그루포 멕시코 소유 — 북미 공급망 핵심" },
  { id: "ironore-southafrica", commodity: "철광석", type: "광물", site: "시셴 광산", country: "남아프리카공화국", region: "노던케이프", lat: -27.78, lng: 22.99, rank: 9, share: 2.5, stakes: [{ holder: "쿰바 아이언 오어(앵글로 아메리칸 계열)", country: "영국", pct: 70 }], owners: "영국 앵글로 아메리칸 계열 쿰바 운영 — 대중국 수출 의존" },
  { id: "ironore-usa", commodity: "철광석", type: "광물", site: "민택 광산", country: "미국", region: "미네소타", lat: 47.53, lng: -92.62, rank: 10, share: 2, stakes: [{ holder: "일본제철(Nippon Steel, U.S. Steel 모회사)", country: "일본", pct: 100 }], owners: "US스틸(일본제철 100% 자회사) 운영 — 2025년 6월 인수 완료, 미 정부 황금주(거부권) 보유" },
  { id: "gold-ghana", commodity: "금", type: "광물", site: "타르콰 광산", country: "가나", region: "웨스턴주", lat: 5.3, lng: -1.99, rank: 9, share: 4, stakes: [{ holder: "골드필즈", country: "남아프리카공화국", pct: 90 }, { holder: "가나 정부", country: "가나", pct: 10 }], owners: "남아공 골드필즈 운영, 가나 정부 10% 지분 — 아프리카 최대 금 생산국" },
  { id: "gold-uzbekistan", commodity: "금", type: "광물", site: "무룬타우 광산", country: "우즈베키스탄", region: "나보이주", lat: 41.5, lng: 64.58, rank: 10, share: 3.5, stakes: [{ holder: "나보이 광업제련콤비나트(NMMC)", country: "우즈베키스탄", pct: 100 }], owners: "우즈베크 국영 NMMC 소유 — 세계 최대 노천 금광" },
  { id: "silver-usa", commodity: "은", type: "광물", site: "그린스크리크 광산", country: "미국", region: "알래스카", lat: 58.08, lng: -134.63, rank: 9, share: 4.5, stakes: [{ holder: "헤클라 마이닝", country: "미국", pct: 100 }], owners: "미국 헤클라 마이닝 소유 — 미국 최대 은 광산" },
  { id: "silver-kazakhstan", commodity: "은", type: "광물", site: "리데르-소콜니 광산", country: "카자흐스탄", region: "동카자흐스탄", lat: 50.34, lng: 83.51, rank: 10, share: 4, stakes: [{ holder: "글렌코어(카즈징크)", country: "스위스", pct: 70 }, { holder: "타우켄 삼룩(국부펀드)", country: "카자흐스탄", pct: 30 }], owners: "스위스 글렌코어가 지배하는 카즈징크 운영 — 러시아 인접 물류 리스크" },
  { id: "lithium-namibia", commodity: "리튬", type: "광물", site: "우이스 광산", country: "나미비아", region: "에롱고주", lat: -21.22, lng: 14.87, rank: 9, share: 1, stakes: [{ holder: "안드라다 마이닝", country: "영국", pct: 100 }], owners: "영국 상장 안드라다 마이닝 운영 — 미가공 원석 수출은 중국계가 주도" },
  { id: "lithium-usa", commodity: "리튬", type: "광물", site: "실버피크 광산", country: "미국", region: "네바다", lat: 37.75, lng: -117.64, rank: 10, share: 0.4, stakes: [{ holder: "앨버말", country: "미국", pct: 100 }], owners: "미국 앨버말 소유 — 미국 유일의 상업 리튬 생산지(염수)" },
  { id: "cobalt-papuanewguinea", commodity: "코발트", type: "광물", site: "라무 광산", country: "파푸아뉴기니", region: "마당주", lat: -5.55, lng: 145.75, rank: 9, share: 1, stakes: [{ holder: "MCC(중국야금과공그룹)", country: "중국", pct: 85 }, { holder: "Nickel 28", country: "캐나다", pct: 8.6 }], owners: "중국 국영 MCC 운영 — 코발트 전량 중국 배터리 공급망행" },
  { id: "cobalt-turkey", commodity: "코발트", type: "광물", site: "괴르데스 광산", country: "튀르키예", region: "마니사주", lat: 38.93, lng: 28.29, rank: 10, share: 0.9, stakes: [{ holder: "메타 니켈 코발트(조를루 홀딩)", country: "튀르키예", pct: 100 }], owners: "튀르키예 조를루 홀딩 계열 운영 — 니켈·코발트 라테라이트 광산" },
  { id: "nickel-colombia", commodity: "니켈", type: "광물", site: "세로 마토소 광산", country: "콜롬비아", region: "코르도바", lat: 7.94, lng: -75.42, rank: 9, share: 1.2, stakes: [{ holder: "CoreX Holding 자회사(구 South32)", country: "튀르키예", pct: 99.9 }], owners: "튀르키예 CoreX Holding 자회사 소유(2025.12 South32에서 인수 완료) — 남미 최대 페로니켈 단일 광산" },
  { id: "nickel-finland", commodity: "니켈", type: "광물", site: "테라파메 소트카모(탈비바라) 광산", country: "핀란드", region: "카이누", lat: 63.97, lng: 28.03, rank: 10, share: 1.1, stakes: [{ holder: "Finnish Minerals Group(핀란드 국영)", country: "핀란드", pct: 56.1 }, { holder: "Galena 펀드(Trafigura 계열 자산운용)", country: "스위스", pct: 39.4 }, { holder: "Mandatum(삼포그룹 계열)", country: "핀란드", pct: 4.5 }], owners: "핀란드 국영 지주회사 주도 — EU 배터리 니켈 자립의 핵심 자산" },
  { id: "rareearth-madagascar", commodity: "희토류", type: "광물", site: "QMM 포르도팽 광산", country: "마다가스카르", region: "아노시", lat: -25.03, lng: 46.98, rank: 9, share: 0.7, stakes: [{ holder: "Rio Tinto", country: "영국", pct: 80 }, { holder: "마다가스카르 정부", country: "마다가스카르", pct: 20 }], owners: "리오틴토 80%·정부 20% — 모나자이트 정광 대부분 중국으로 수출" },
  { id: "rareearth-brazil", commodity: "희토류", type: "광물", site: "세하 베르지 광산", country: "브라질", region: "고이아스", lat: -13.53, lng: -48.22, rank: 10, share: 0.5, stakes: [{ holder: "Denham Capital", country: "미국", pct: null }, { holder: "Vision Blue Resources", country: "영국", pct: null }], owners: "미·영 사모자본 소유 — 아시아 밖 첫 이온흡착점토형 희토류 광산" },
  { id: "bauxite-saudiarabia", commodity: "보크사이트", type: "광물", site: "알바이타 광산", country: "사우디아라비아", region: "카심주", lat: 27.56, lng: 44.2, rank: 9, share: 1.3, stakes: [{ holder: "Ma'aden(마덴)", country: "사우디아라비아", pct: 100 }], owners: "사우디 국영 광업사 마덴 소유 — 알코아 합작 지분 인수로 완전 자국화" },
  { id: "bauxite-kazakhstan", commodity: "보크사이트", type: "광물", site: "크라스노옥탸브리스코예 광산", country: "카자흐스탄", region: "코스타나이주", lat: 52.5, lng: 62.5, rank: 10, share: 1.1, stakes: [{ holder: "ERG(유라시안리소시스그룹)", country: "룩셈부르크", pct: 100 }], owners: "룩셈부르크 본사 ERG 소유 — 카자흐 정부가 그룹 지분 40% 보유" },
  { id: "platinum-australia", commodity: "백금족", type: "광물", site: "마운트 키스 광산", country: "호주", region: "웨스턴오스트레일리아", lat: -27.25, lng: 120.55, rank: 9, share: 0.5, stakes: [{ holder: "BHP", country: "호주", pct: 100 }], owners: "호주 광산 메이저 BHP 소유 — 니켈 부산물로 PGM을 회수했으나 니켈 공급과잉·가격 급락으로 2024.10부터 WA 니켈 전체 일시 전면중단(care & maintenance), 재개 여부 2027.2까지 재검토(순위는 중단 전 기준)" },
  { id: "platinum-serbia", commodity: "백금족", type: "광물", site: "보르 구리 광산", country: "세르비아", region: "보르", lat: 44.08, lng: 22.1, rank: 10, share: 0.2, stakes: [{ holder: "Zijin Mining(쯔진마이닝)", country: "중국", pct: 63 }, { holder: "세르비아 정부", country: "세르비아", pct: 37 }], owners: "중국 쯔진마이닝 지배 — 구리 정련 부산물로 PGM 회수, 발칸 내 중국 거점" },
  { id: "uranium-india", commodity: "우라늄", type: "에너지", site: "자두구다 광산", country: "인도", region: "자르칸드", lat: 22.65, lng: 86.35, rank: 9, share: 0.8, stakes: [{ holder: "UCIL(인도우라늄공사)", country: "인도", pct: 100 }], owners: "인도 국영 UCIL 소유 — 전량 자국 원전용, 수출 없는 폐쇄적 공급망" },
  { id: "uranium-ukraine", commodity: "우라늄", type: "에너지", site: "잉굴스카 광산", country: "우크라이나", region: "키로보흐라드주", lat: 48.5, lng: 32.25, rank: 10, share: 0.5, stakes: [{ holder: "SkhidGZK(동부광업선광콤비나트)", country: "우크라이나", pct: 100 }], owners: "우크라이나 국영 소유 — 전쟁 속 러시아산 핵연료 탈피의 전략 자산" },
  { id: "coal-mongolia", commodity: "석탄", type: "에너지", site: "타반톨고이 광산", country: "몽골", region: "우므느고비(남고비)", lat: 43.62, lng: 105.48, rank: 9, share: 1.2, stakes: [{ holder: "Erdenes Tavan Tolgoi(몽골 국영)", country: "몽골", pct: 100 }], owners: "몽골 국영기업 소유 — 원료탄 수출을 사실상 중국 한 곳에 의존" },
  { id: "coal-germany", commodity: "석탄", type: "에너지", site: "가르츠바일러 광산", country: "독일", region: "노르트라인베스트팔렌", lat: 51.06, lng: 6.51, rank: 10, share: 1.0, stakes: [{ holder: "RWE", country: "독일", pct: 100 }], owners: "독일 전력사 RWE 소유 — 2030년 탈석탄 계획으로 단계적 폐쇄 예정" },
  { id: "oil-iran", commodity: "원유", type: "에너지", site: "아바즈 유전 (후제스탄)", country: "이란", region: "후제스탄주", lat: 31.32, lng: 48.68, rank: 9, share: 4, stakes: [{ holder: "NIOC(이란국영석유회사)", country: "이란", pct: 100 }], owners: "국영 NIOC 독점 — 서방 제재 속 중국행 '그림자 함대' 수출에 의존" },
  { id: "oil-kuwait", commodity: "원유", type: "에너지", site: "부르간 유전", country: "쿠웨이트", region: "쿠웨이트 남동부", lat: 29.0, lng: 47.92, rank: 10, share: 3, stakes: [{ holder: "쿠웨이트석유공사(KOC/KPC)", country: "쿠웨이트", pct: 100 }], owners: "국영 KPC 산하 KOC 독점 — OPEC+ 감산 공조의 핵심 걸프 산유국" },
  { id: "gas-saudiarabia", commodity: "천연가스", type: "에너지", site: "자푸라 셰일가스전", country: "사우디아라비아", region: "동부주", lat: 24.5, lng: 49.8, rank: 9, share: 2.7, stakes: [{ holder: "사우디 아람코", country: "사우디아라비아", pct: 100 }], owners: "아람코 단독 개발 — 원유 의존 탈피 위해 중동 최대 비전통 가스전 육성" },
  { id: "gas-algeria", commodity: "천연가스", type: "에너지", site: "하시 르멜 가스전", country: "알제리", region: "사하라 북부", lat: 32.93, lng: 3.25, rank: 10, share: 2.5, stakes: [{ holder: "소나트라크(Sonatrach)", country: "알제리", pct: 100 }], owners: "국영 소나트라크 주도 — 지중해 파이프라인으로 남유럽의 탈러시아 대체 공급원" },
  { id: "soybean-ukraine", commodity: "대두", type: "농산물", site: "폴타바 중부 흑토지대", country: "우크라이나", region: "폴타바주", lat: 49.59, lng: 34.55, rank: 9, share: 1.5, stakes: [{ holder: "케르넬(Kernel)", country: "우크라이나", pct: null }, { holder: "니불론(Nibulon)", country: "우크라이나", pct: null }], owners: "민간 농기업 케르넬·니불론 주도 — 전쟁 중 흑해 항로가 수출 생명선" },
  { id: "soybean-bolivia", commodity: "대두", type: "농산물", site: "산타크루스 저지대", country: "볼리비아", region: "산타크루스주", lat: -17.78, lng: -63.18, rank: 10, share: 0.9, stakes: [{ holder: "ANAPO(대두생산자협회)", country: "볼리비아", pct: null }], owners: "산타크루스 민간 농가·ANAPO 중심 — 내륙국 특성상 대두박 가공 후 역내·중국 수출" },
  { id: "wheat-ukraine", commodity: "밀", type: "농산물", site: "오데사 남부 스텝 곡창지대", country: "우크라이나", region: "오데사·미콜라이우 스텝", lat: 47.0, lng: 31.0, rank: 9, share: 2.9, stakes: [{ holder: "니불론(Nibulon)", country: "우크라이나", pct: null }, { holder: "케르넬(Kernel)", country: "우크라이나", pct: null }], owners: "민간 곡물기업 주도 — 흑해 수출 회랑이 세계 식량안보의 최대 변수" },
  { id: "wheat-turkey", commodity: "밀", type: "농산물", site: "코니아 평원 (중앙 아나톨리아)", country: "튀르키예", region: "코니아주", lat: 37.87, lng: 32.49, rank: 10, share: 2.6, stakes: [{ holder: "TMO(튀르키예곡물청)", country: "튀르키예", pct: null }], owners: "국영 곡물청 TMO가 수매·비축 통제 — 러·우 밀을 재가공하는 세계 1위 밀가루 수출국" },
  { id: "corn-southafrica", commodity: "옥수수", type: "농산물", site: "프리스테이트 옥수수 삼각지대", country: "남아프리카공화국", region: "프리스테이트주", lat: -27.39, lng: 26.62, rank: 9, share: 1.4, stakes: [{ holder: "그레인SA(생산자단체)", country: "남아프리카공화국", pct: null }, { holder: "센웨스(Senwes)", country: "남아프리카공화국", pct: null }], owners: "민간 상업농·SAFEX 선물시장 중심 — 가뭄 시 남부 아프리카 전체 식량 수급 좌우" },
  { id: "corn-russia", commodity: "옥수수", type: "농산물", site: "크라스노다르 쿠반 평야", country: "러시아", region: "크라스노다르 지방", lat: 45.04, lng: 38.98, rank: 10, share: 1.2, stakes: [{ holder: "대형 농기업(아그로콤플렉스 등)", country: "러시아", pct: null }], owners: "크렘린의 수출쿼터·관세 통제 아래 대형 농기업 주도 — 중동·아시아향 수출 확대" },
  { id: "palm-cotedivoire", commodity: "팜유", type: "농산물", site: "아보이소 팜오일 벨트 (남동부)", country: "코트디부아르", region: "코모에 남부", lat: 5.47, lng: -3.21, rank: 9, share: 0.7, stakes: [{ holder: "팜시(PALMCI, SIFCA그룹)", country: "코트디부아르", pct: null }], owners: "SIFCA그룹 계열 팜시 주도 — 서아프리카 역내 식용유 수요를 채우는 지역 공급 거점" },
  { id: "palm-brazil", commodity: "팜유", type: "농산물", site: "파라주 토메아수 팜 벨트", country: "브라질", region: "파라주 (아마존)", lat: -2.42, lng: -48.15, rank: 10, share: 0.7, stakes: [{ holder: "아그로팔마(Agropalma)", country: "브라질", pct: null }, { holder: "브라질바이오퓨얼스(BBF)", country: "브라질", pct: null }], owners: "아그로팔마·BBF 등 민간 주도 — '산림전용 없는' 인증 팜유로 동남아산과 차별화" },
];
/* ============================================================
   매장량(reserves) 상위 10 — 광물·에너지만
   ------------------------------------------------------------
   metric: "reserve"  (생산량 항목은 metric 없거나 "production")
   농산물(밀·대두·옥수수·팜유)은 매장 개념이 없어 제외.
   출처: USGS MCS, OPEC, BP/EI Statistical Review 등 공개 통계 근사.
   share = 세계 매장 점유율(%) 근사. 검증·갱신 권장.
   ============================================================ */

// ---- 구리 매장 ----
COMMODITIES.push(
  { id: "copper-r-chile", commodity: "구리", type: "광물", metric: "reserve", site: "추키카마타·에스콘디다 벨트", country: "칠레", region: "안토파가스타·아타카마", lat: -22.3, lng: -68.9, rank: 1, share: 18, amount: 180, unit: "백만 t", stakes: [{ holder: "Codelco", country: "칠레", pct: null }, { holder: "BHP·기타", country: "호주 등", pct: null }], owners: "국영 Codelco + 다국적 광산기업 — 세계 최대 구리 매장국" },
  { id: "copper-r-australia", commodity: "구리", type: "광물", metric: "reserve", site: "올림픽댐·마운트아이사", country: "호주", region: "사우스·퀸즐랜드", lat: -27.5, lng: 140.5, rank: 2, share: 10, amount: 100, unit: "백만 t", stakes: [{ holder: "BHP", country: "호주", pct: null }, { holder: "Glencore", country: "스위스", pct: null }], owners: "다국적 광산기업 과점" },
  { id: "copper-r-peru", commodity: "구리", type: "광물", metric: "reserve", site: "안타미나·라스밤바스 벨트", country: "페루", region: "안데스", lat: -13.0, lng: -74.5, rank: 3, share: 8.7, amount: 85, unit: "백만 t", stakes: [{ holder: "다국적 컨소시엄", country: "호주·스위스·중국 등", pct: null }], owners: "다국적 컨소시엄 — 생산·매장 모두 상위" },
  { id: "copper-r-russia", commodity: "구리", type: "광물", metric: "reserve", site: "우도칸·노릴스크", country: "러시아", region: "시베리아·극동", lat: 56.7, lng: 118.3, rank: 4, share: 8, amount: 80, unit: "백만 t", stakes: [{ holder: "Udokan Copper·Nornickel", country: "러시아", pct: null }], owners: "러시아 자본 지배 — 미개발 대형 매장 다수" },
  { id: "copper-r-mexico", commodity: "구리", type: "광물", metric: "reserve", site: "소노라 구리벨트", country: "멕시코", region: "소노라", lat: 30.5, lng: -110.5, rank: 6, share: 5.5, amount: 53, unit: "백만 t", stakes: [{ holder: "Grupo México", country: "멕시코", pct: null }], owners: "멕시코 재벌 주도" },
  { id: "copper-r-usa", commodity: "구리", type: "광물", metric: "reserve", site: "애리조나 구리벨트", country: "미국", region: "애리조나", lat: 33.2, lng: -110.8, rank: 7, share: 5, amount: 47, unit: "백만 t", stakes: [{ holder: "Freeport-McMoRan", country: "미국", pct: null }], owners: "미국 민간기업 주도" },
  { id: "copper-r-indonesia", commodity: "구리", type: "광물", metric: "reserve", site: "그라스버그·바투히자우", country: "인도네시아", region: "파푸아·누사틍가라", lat: -4.1, lng: 136.5, rank: 10, share: 2, amount: 21, unit: "백만 t", stakes: [{ holder: "Freeport·Inalum", country: "미국·인도네시아", pct: null }], owners: "국영 지분 + 미국 운영" },
  { id: "copper-r-china", commodity: "구리", type: "광물", metric: "reserve", site: "장시·티베트 동광", country: "중국", region: "장시·티베트", lat: 30.5, lng: 100.0, rank: 8, share: 4, amount: 41, unit: "백만 t", stakes: [{ holder: "Jiangxi Copper 등", country: "중국", pct: null }], owners: "국영기업 지배 — 생산 대비 매장 비중은 낮음" },
  { id: "copper-r-poland", commodity: "구리", type: "광물", metric: "reserve", site: "레그니차-그워구프(루빈) 구리벨트", country: "폴란드", region: "하실레지아", lat: 51.4, lng: 16.2, rank: 9, share: 3.5, amount: 33, unit: "백만 t", stakes: [{ holder: "KGHM", country: "폴란드", pct: null }], owners: "국영 지분 지배 — 유럽 최대 구리 매장" },
  { id: "copper-r-drc", commodity: "구리", type: "광물", metric: "reserve", site: "카모아-카쿨라·카탄가 벨트", country: "콩고민주공화국", region: "루알라바", lat: -10.73, lng: 25.38, rank: 5, share: 8, amount: 80, unit: "백만 t", stakes: [{ holder: "Ivanhoe Mines·Zijin 등", country: "캐나다·중국", pct: null }], owners: "중국 자본 깊이 관여 — 매장 러시아와 사실상 공동 4~5위" },
);

// ---- 철광석 매장 ----
COMMODITIES.push(
  { id: "ironore-r-australia", commodity: "철광석", type: "광물", metric: "reserve", site: "필바라 분지", country: "호주", region: "웨스턴오스트레일리아", lat: -22.5, lng: 118.5, rank: 1, share: 30, amount: 580, unit: "억 t", stakes: [{ holder: "BHP·Rio Tinto·Fortescue", country: "호주", pct: null }], owners: "다국적 광산기업 과점 — 세계 최대 철광 매장·생산" },
  { id: "ironore-r-brazil", commodity: "철광석", type: "광물", metric: "reserve", site: "카라자스·미나스 철광", country: "브라질", region: "파라·미나스", lat: -6.5, lng: -50.0, rank: 2, share: 15, amount: 340, unit: "억 t", stakes: [{ holder: "Vale", country: "브라질", pct: null }], owners: "기관투자자 분산 소유" },
  { id: "ironore-r-russia", commodity: "철광석", type: "광물", metric: "reserve", site: "쿠르스크 자기이상대(KMA)", country: "러시아", region: "쿠르스크·벨고로드", lat: 51.7, lng: 36.2, rank: 3, share: 14, amount: 250, unit: "억 t", stakes: [{ holder: "Metalloinvest 등", country: "러시아", pct: null }], owners: "러시아 과두자본 지배" },
  { id: "ironore-r-china", commodity: "철광석", type: "광물", metric: "reserve", site: "안산·바이윈 철광", country: "중국", region: "랴오닝·네이멍구", lat: 41.5, lng: 123.0, rank: 4, share: 12, amount: 200, unit: "억 t", stakes: [{ holder: "Ansteel·국영", country: "중국", pct: null }], owners: "국영기업 지배 — 저품위 매장 비중 큼" },
  { id: "ironore-r-ukraine", commodity: "철광석", type: "광물", metric: "reserve", site: "크리비리흐 분지", country: "우크라이나", region: "드니프로", lat: 47.9, lng: 33.4, rank: 5, share: 4, amount: 65, unit: "억 t", stakes: [{ holder: "Metinvest 등", country: "우크라이나", pct: null }], owners: "우크라이나 과두자본 — 전쟁 영향" },
  { id: "ironore-r-canada", commodity: "철광석", type: "광물", metric: "reserve", site: "라브라도 트로프", country: "캐나다", region: "퀘벡·뉴펀들랜드", lat: 53.0, lng: -67.0, rank: 6, share: 3.5, amount: 60, unit: "억 t", stakes: [{ holder: "IOC·ArcelorMittal 등", country: "캐나다·룩셈부르크", pct: null }], owners: "다국적 철강·광산기업" },
  { id: "ironore-r-india", commodity: "철광석", type: "광물", metric: "reserve", site: "오디샤·차티스가르 철광", country: "인도", region: "오디샤", lat: 21.5, lng: 85.0, rank: 7, share: 3, amount: 55, unit: "억 t", stakes: [{ holder: "NMDC·SAIL 등", country: "인도", pct: null }], owners: "국영기업 지배" },
  { id: "ironore-r-usa", commodity: "철광석", type: "광물", metric: "reserve", site: "메사비 산맥", country: "미국", region: "미네소타", lat: 47.5, lng: -92.5, rank: 8, share: 2, amount: 30, unit: "억 t", stakes: [{ holder: "U.S. Steel·Cleveland-Cliffs", country: "미국", pct: null }], owners: "미국 철강사 소유" },
  { id: "ironore-r-iran", commodity: "철광석", type: "광물", metric: "reserve", site: "골에고하르·차도가르", country: "이란", region: "케르만", lat: 29.1, lng: 55.3, rank: 9, share: 2, amount: 27, unit: "억 t", stakes: [{ holder: "국영계열", country: "이란", pct: null }], owners: "국영·준국영 지배" },
  { id: "ironore-r-kazakhstan", commodity: "철광석", type: "광물", metric: "reserve", site: "소콜로프·사르바이", country: "카자흐스탄", region: "코스타나이", lat: 53.0, lng: 63.0, rank: 10, share: 1.5, amount: 25, unit: "억 t", stakes: [{ holder: "ERG", country: "룩셈부르크", pct: null }], owners: "ERG + 국가 지분" },
);

// ---- 금 매장 ----
COMMODITIES.push(
  { id: "gold-r-australia", commodity: "금", type: "광물", metric: "reserve", site: "칼굴리·슈퍼피트 벨트", country: "호주", region: "웨스턴오스트레일리아", lat: -30.7, lng: 121.5, rank: 1, share: 20, amount: 13000, unit: "t", stakes: [{ holder: "Newmont·Northern Star 등", country: "미국·호주", pct: null }], owners: "다국적·호주 금광 기업 — 세계 최대 금 매장국" },
  { id: "gold-r-russia", commodity: "금", type: "광물", metric: "reserve", site: "시베리아·극동 금광대", country: "러시아", region: "크라스노야르스크·마가단", lat: 60.0, lng: 100.0, rank: 2, share: 18, amount: 12000, unit: "t", stakes: [{ holder: "Polyus·기타", country: "러시아", pct: null }], owners: "러시아 과두·국영 혼재" },
  { id: "gold-r-southafrica", commodity: "금", type: "광물", metric: "reserve", site: "비트바테르스란드", country: "남아프리카공화국", region: "하우텡·프리스테이트", lat: -26.2, lng: 28.0, rank: 3, share: 9, amount: 5000, unit: "t", stakes: [{ holder: "Sibanye·Harmony 등", country: "남아공", pct: null }], owners: "남아공 금광 기업 — 심부 매장, 생산은 과거 대비 감소" },
  { id: "gold-r-usa", commodity: "금", type: "광물", metric: "reserve", site: "네바다 금벨트", country: "미국", region: "네바다", lat: 40.8, lng: -116.5, rank: 4, share: 6, amount: 3000, unit: "t", stakes: [{ holder: "Barrick·Newmont", country: "캐나다·미국", pct: null }], owners: "다국적 합작 소유" },
  { id: "gold-r-indonesia", commodity: "금", type: "광물", metric: "reserve", site: "그라스버그(금·구리)", country: "인도네시아", region: "파푸아", lat: -4.05, lng: 137.1, rank: 5, share: 5, amount: 2600, unit: "t", stakes: [{ holder: "Freeport·Inalum", country: "미국·인도네시아", pct: null }], owners: "국영 지분 과반 + 미국 운영" },
  { id: "gold-r-brazil", commodity: "금", type: "광물", metric: "reserve", site: "파라·미나스 금광", country: "브라질", region: "파라", lat: -6.0, lng: -51.0, rank: 6, share: 4, amount: 2400, unit: "t", stakes: [{ holder: "Kinross·현지", country: "캐나다·브라질", pct: null }], owners: "외국·현지 자본 혼재" },
  { id: "gold-r-canada", commodity: "금", type: "광물", metric: "reserve", site: "애비티비 금벨트", country: "캐나다", region: "온타리오·퀘벡", lat: 48.5, lng: -79.0, rank: 7, share: 4, amount: 2300, unit: "t", stakes: [{ holder: "Agnico·기타", country: "캐나다", pct: null }], owners: "기관투자자 분산 소유" },
  { id: "gold-r-china", commodity: "금", type: "광물", metric: "reserve", site: "산둥·허난 금광", country: "중국", region: "산둥성", lat: 37.4, lng: 120.3, rank: 8, share: 3.5, amount: 2000, unit: "t", stakes: [{ holder: "Shandong Gold·Zijin", country: "중국", pct: null }], owners: "국영·민간 중국기업 — 생산 1위, 매장은 중위" },
  { id: "gold-r-uzbekistan", commodity: "금", type: "광물", metric: "reserve", site: "무룬타우", country: "우즈베키스탄", region: "나보이", lat: 41.5, lng: 64.6, rank: 9, share: 3, amount: 1800, unit: "t", stakes: [{ holder: "NMMC", country: "우즈베키스탄", pct: 100 }], owners: "국영 NMMC — 세계 최대급 노천 금광" },
  { id: "gold-r-ghana", commodity: "금", type: "광물", metric: "reserve", site: "아산티 금벨트", country: "가나", region: "아산티·웨스턴", lat: 6.2, lng: -1.6, rank: 10, share: 2.5, amount: 1000, unit: "t", stakes: [{ holder: "Gold Fields·Newmont 등", country: "남아공·미국", pct: null }], owners: "외국 광산 + 정부 지분" },
);

// ---- 은 매장 ----
COMMODITIES.push(
  { id: "silver-r-peru", commodity: "은", type: "광물", metric: "reserve", site: "안데스 다금속 벨트", country: "페루", region: "안카시·파스코", lat: -10.7, lng: -76.3, rank: 1, share: 18, amount: 110, unit: "천 t", stakes: [{ holder: "다국적·현지 광산", country: "페루 등", pct: null }], owners: "구리·납아연 부산물 은 — 세계 최대 은 매장국" },
  { id: "silver-r-australia", commodity: "은", type: "광물", metric: "reserve", site: "캐닝턴·브로큰힐", country: "호주", region: "퀸즐랜드·NSW", lat: -21.9, lng: 140.9, rank: 2, share: 14, amount: 94, unit: "천 t", stakes: [{ holder: "South32 등", country: "호주", pct: null }], owners: "기관투자자 분산 소유" },
  { id: "silver-r-russia", commodity: "은", type: "광물", metric: "reserve", site: "두캇·극동 은광", country: "러시아", region: "마가단", lat: 62.5, lng: 155.0, rank: 3, share: 10, amount: 92, unit: "천 t", stakes: [{ holder: "Polymetal 등", country: "러시아", pct: null }], owners: "러시아 자본 지배" },
  { id: "silver-r-poland", commodity: "은", type: "광물", metric: "reserve", site: "루빈 구리·은 광상", country: "폴란드", region: "하실레지아", lat: 51.4, lng: 16.2, rank: 5, share: 7, amount: 59, unit: "천 t", stakes: [{ holder: "KGHM", country: "폴란드", pct: null }], owners: "국영 지분 지배 — 유럽 최대 은 매장" },
  { id: "silver-r-china", commodity: "은", type: "광물", metric: "reserve", site: "허난·윈난 부산물 은", country: "중국", region: "허난", lat: 34.0, lng: 111.0, rank: 4, share: 9, amount: 67, unit: "천 t", stakes: [{ holder: "중국 광산기업", country: "중국", pct: null }], owners: "국영·민간 혼재" },
  { id: "silver-r-mexico", commodity: "은", type: "광물", metric: "reserve", site: "사카테카스·두랑고 은광", country: "멕시코", region: "사카테카스", lat: 23.2, lng: -102.9, rank: 6, share: 6, amount: 37, unit: "천 t", stakes: [{ holder: "Fresnillo 등", country: "멕시코·영국", pct: null }], owners: "생산 1위이나 매장 순위는 중상위" },
  { id: "silver-r-chile", commodity: "은", type: "광물", metric: "reserve", site: "북부 구리 부산물 은", country: "칠레", region: "안토파가스타", lat: -24.3, lng: -69.1, rank: 7, share: 5, amount: 26, unit: "천 t", stakes: [{ holder: "BHP·Codelco 등", country: "호주·칠레", pct: null }], owners: "구리 광산 부산물" },
  { id: "silver-r-usa", commodity: "은", type: "광물", metric: "reserve", site: "알래스카·아이다호 은광", country: "미국", region: "알래스카", lat: 58.1, lng: -134.6, rank: 8, share: 4, amount: 26, unit: "천 t", stakes: [{ holder: "Hecla 등", country: "미국", pct: null }], owners: "미국 상장 광산기업" },
  { id: "silver-r-bolivia", commodity: "은", type: "광물", metric: "reserve", site: "포토시·산크리스토발", country: "볼리비아", region: "포토시", lat: -21.1, lng: -67.2, rank: 9, share: 4, amount: 22, unit: "천 t", stakes: [{ holder: "Sumitomo·국영", country: "일본·볼리비아", pct: null }], owners: "외국·국영 혼재" },
  { id: "silver-r-kazakhstan", commodity: "은", type: "광물", metric: "reserve", site: "동카자흐 다금속", country: "카자흐스탄", region: "동카자흐스탄", lat: 50.3, lng: 83.5, rank: 10, share: 3, amount: 20, unit: "천 t", stakes: [{ holder: "Kazzinc(Glencore)", country: "스위스·카자흐", pct: null }], owners: "글렌코어 계열 주도" },
);

// ---- 리튬 매장 ----
COMMODITIES.push(
  { id: "lithium-r-chile", commodity: "리튬", type: "광물", metric: "reserve", site: "아타카마 염호", country: "칠레", region: "안토파가스타", lat: -23.5, lng: -68.2, rank: 1, share: 36, amount: 9.3, unit: "백만 t Li", stakes: [{ holder: "SQM·Albemarle", country: "칠레·미국", pct: null }], owners: "국가 통제 강화 + 민간 운영 — 세계 최대 리튬 매장" },
  { id: "lithium-r-australia", commodity: "리튬", type: "광물", metric: "reserve", site: "그린부시스·필바라 경암", country: "호주", region: "웨스턴오스트레일리아", lat: -32.0, lng: 118.0, rank: 2, share: 22, amount: 6.2, unit: "백만 t Li", stakes: [{ holder: "Albemarle·Tianqi·IGO 등", country: "미국·중국·호주", pct: null }], owners: "생산 1위, 매장 2위 — 경암(스포듀민) 중심" },
  { id: "lithium-r-argentina", commodity: "리튬", type: "광물", metric: "reserve", site: "리튬 삼각 염호", country: "아르헨티나", region: "카타마르카·후후이", lat: -24.5, lng: -67.0, rank: 3, share: 12, amount: 3.6, unit: "백만 t Li", stakes: [{ holder: "Rio Tinto(구 Arcadium)·POSCO 등", country: "영국·호주·한국 등", pct: null }], owners: "외국 자본 주도 개발 — 매장 상위·생산 추격" },
  { id: "lithium-r-china", commodity: "리튬", type: "광물", metric: "reserve", site: "칭하이 염호·장시 경암", country: "중국", region: "칭하이·장시", lat: 36.5, lng: 98.0, rank: 4, share: 8, amount: 3.0, unit: "백만 t Li", stakes: [{ holder: "Ganfeng·CATL 등", country: "중국", pct: null }], owners: "중국 민간·국영 — 정련 능력과 결합" },
  { id: "lithium-r-usa", commodity: "리튬", type: "광물", metric: "reserve", site: "클레이톤밸리·킹스밸리", country: "미국", region: "네바다", lat: 38.0, lng: -118.0, rank: 5, share: 5, amount: 1.1, unit: "백만 t Li", stakes: [{ holder: "Albemarle·개발사", country: "미국", pct: null }], owners: "미국 상장·개발사 — 생산은 아직 소규모" },
  { id: "lithium-r-canada", commodity: "리튬", type: "광물", metric: "reserve", site: "퀘벡·온타리오 경암", country: "캐나다", region: "퀘벡", lat: 48.5, lng: -77.5, rank: 6, share: 3, amount: 0.9, unit: "백만 t Li", stakes: [{ holder: "Sayona·기타", country: "호주·캐나다", pct: null }], owners: "외국·현지 합작" },
  { id: "lithium-r-zimbabwe", commodity: "리튬", type: "광물", metric: "reserve", site: "비키타·아카디아", country: "짐바브웨", region: "마스빙고", lat: -20.1, lng: 31.4, rank: 8, share: 2, amount: 0.3, unit: "백만 t Li", stakes: [{ holder: "Sinomine·중국계", country: "중국", pct: null }], owners: "중국 자본 깊이 관여" },
  { id: "lithium-r-brazil", commodity: "리튬", type: "광물", metric: "reserve", site: "미나스제라이스 경암", country: "브라질", region: "미나스제라이스", lat: -16.8, lng: -42.1, rank: 7, share: 2.5, amount: 0.4, unit: "백만 t Li", stakes: [{ holder: "Sigma·AMG 등", country: "캐나다·네덜란드", pct: null }], owners: "외국 자본 주도" },
  { id: "lithium-r-portugal", commodity: "리튬", type: "광물", metric: "reserve", site: "바로주·이베리아 벨트", country: "포르투갈", region: "노르트", lat: 41.7, lng: -7.7, rank: 9, share: 1.5, amount: 0.1, unit: "백만 t Li", stakes: [{ holder: "Savannah 등", country: "영국", pct: null }], owners: "유럽 내 소수 매장 — 개발 지연" },
  { id: "lithium-r-bolivia", commodity: "리튬", type: "광물", metric: "reserve", site: "우유니 염호", country: "볼리비아", region: "포토시", lat: -20.2, lng: -67.5, rank: 10, share: 1.5, amount: 0.2, unit: "백만 t Li", stakes: [{ holder: "YLB(국영)·합작", country: "볼리비아", pct: null }], owners: "자원량은 세계 최대급이나 확인 매장·생산은 제한적" },
);

// ---- 코발트 매장 ----
COMMODITIES.push(
  { id: "cobalt-r-drc", commodity: "코발트", type: "광물", metric: "reserve", site: "카탄가 구리·코발트벨트", country: "콩고민주공화국", region: "루알라바·오트카탕가", lat: -10.7, lng: 25.5, rank: 1, share: 55, amount: 6.0, unit: "백만 t", stakes: [{ holder: "CMOC·Glencore·Gécamines", country: "중국·스위스·DRC", pct: null }], owners: "중국 자본 깊이 관여 — 생산·매장 모두 압도적 1위" },
  { id: "cobalt-r-australia", commodity: "코발트", type: "광물", metric: "reserve", site: "머린머린·니켈 부산물", country: "호주", region: "웨스턴오스트레일리아", lat: -28.7, lng: 121.9, rank: 2, share: 16, amount: 1.7, unit: "백만 t", stakes: [{ holder: "Glencore 등", country: "스위스", pct: null }], owners: "니켈 부산물 중심" },
  { id: "cobalt-r-indonesia", commodity: "코발트", type: "광물", metric: "reserve", site: "술라웨시 HPAL 벨트", country: "인도네시아", region: "술라웨시", lat: -2.7, lng: 122.0, rank: 3, share: 6, amount: 0.6, unit: "백만 t", stakes: [{ holder: "중국계 HPAL 합작", country: "중국·인도네시아", pct: null }], owners: "생산 급증, 매장 추격" },
  { id: "cobalt-r-cuba", commodity: "코발트", type: "광물", metric: "reserve", site: "모아·니카로 니켈·코발트", country: "쿠바", region: "올긴", lat: 20.65, lng: -74.95, rank: 4, share: 5, amount: 0.5, unit: "백만 t", stakes: [{ holder: "Sherritt·국영", country: "캐나다·쿠바", pct: null }], owners: "국영 + 외국 합작 — 매장 상위·생산 소규모" },
  { id: "cobalt-r-philippines", commodity: "코발트", type: "광물", metric: "reserve", site: "수리가오 라테라이트", country: "필리핀", region: "카라가", lat: 9.8, lng: 125.5, rank: 5, share: 3, amount: 0.3, unit: "백만 t", stakes: [{ holder: "Nickel Asia 등", country: "필리핀", pct: null }], owners: "현지 + 일본 투자" },
  { id: "cobalt-r-russia", commodity: "코발트", type: "광물", metric: "reserve", site: "노릴스크 니켈 부산물", country: "러시아", region: "크라스노야르스크", lat: 69.3, lng: 88.2, rank: 6, share: 3, amount: 0.3, unit: "백만 t", stakes: [{ holder: "Nornickel", country: "러시아", pct: null }], owners: "러시아 과두자본 지배" },
  { id: "cobalt-r-canada", commodity: "코발트", type: "광물", metric: "reserve", site: "서드베리·밴더호프", country: "캐나다", region: "온타리오", lat: 46.5, lng: -81.0, rank: 7, share: 2.5, amount: 0.2, unit: "백만 t", stakes: [{ holder: "Vale·Glencore", country: "브라질·스위스", pct: null }], owners: "다국적 광산기업" },
  { id: "cobalt-r-madagascar", commodity: "코발트", type: "광물", metric: "reserve", site: "암바토비", country: "마다가스카르", region: "토아마시나", lat: -18.8, lng: 48.3, rank: 8, share: 1.5, amount: 0.1, unit: "백만 t", stakes: [{ holder: "Sumitomo·KORES 등", country: "일본·한국", pct: null }], owners: "외국 자본 주도" },
  { id: "cobalt-r-china", commodity: "코발트", type: "광물", metric: "reserve", site: "진촨 부산물", country: "중국", region: "간쑤", lat: 38.5, lng: 102.2, rank: 9, share: 1.5, amount: 0.1, unit: "백만 t", stakes: [{ holder: "Jinchuan", country: "중국", pct: null }], owners: "국영 — 정련·수입 의존 구조" },
  { id: "cobalt-r-usa", commodity: "코발트", type: "광물", metric: "reserve", site: "아이다호·미네소타 탐사", country: "미국", region: "아이다호", lat: 45.2, lng: -114.3, rank: 10, share: 1, amount: 0.07, unit: "백만 t", stakes: [{ holder: "개발·탐사 기업", country: "미국", pct: null }], owners: "생산 미미, 전략 비축·개발 추진" },
);

// ---- 니켈 매장 ----
COMMODITIES.push(
  { id: "nickel-r-indonesia", commodity: "니켈", type: "광물", metric: "reserve", site: "술라웨시·할마헤라 라테라이트", country: "인도네시아", region: "술라웨시", lat: -2.6, lng: 121.4, rank: 1, share: 22, amount: 55, unit: "백만 t", stakes: [{ holder: "Vale·중국계 제련", country: "브라질·중국·인도네시아", pct: null }], owners: "생산·매장 모두 1위권 — 중국 제련 자본 집중" },
  { id: "nickel-r-australia", commodity: "니켈", type: "광물", metric: "reserve", site: "골드필즈(캄발다·레인스터·마운트키스) 벨트", country: "호주", region: "웨스턴오스트레일리아", lat: -27.3, lng: 120.6, rank: 2, share: 21, amount: 24, unit: "백만 t", stakes: [{ holder: "BHP·기타", country: "호주", pct: null }], owners: "매장 상위 — BHP Nickel West 전면 가동중단(2024.10~ care & maintenance, 2027.2 재검토)" },
  { id: "nickel-r-brazil", commodity: "니켈", type: "광물", metric: "reserve", site: "온사·고이아스 니켈", country: "브라질", region: "파라·고이아스", lat: -6.6, lng: -51.1, rank: 3, share: 16, amount: 16, unit: "백만 t", stakes: [{ holder: "Vale", country: "브라질", pct: null }], owners: "기관투자자 분산 소유" },
  { id: "nickel-r-russia", commodity: "니켈", type: "광물", metric: "reserve", site: "노릴스크·콜라", country: "러시아", region: "크라스노야르스크", lat: 69.3, lng: 88.2, rank: 4, share: 7, amount: 7.5, unit: "백만 t", stakes: [{ holder: "Nornickel", country: "러시아", pct: null }], owners: "러시아 과두자본 지배" },
  { id: "nickel-r-newcaledonia", commodity: "니켈", type: "광물", metric: "reserve", site: "고로·코니앙보", country: "프랑스(뉴칼레도니아)", region: "뉴칼레도니아", lat: -22.3, lng: 166.9, rank: 5, share: 7, amount: 7.1, unit: "백만 t", stakes: [{ holder: "Prony·SLN 등", country: "뉴칼레도니아·프랑스", pct: null }], owners: "현지·프랑스 자본 — 매장 대비 정치·원가 리스크" },
  { id: "nickel-r-philippines", commodity: "니켈", type: "광물", metric: "reserve", site: "수리가오·팔라완", country: "필리핀", region: "카라가", lat: 9.8, lng: 125.5, rank: 7, share: 5, amount: 4.8, unit: "백만 t", stakes: [{ holder: "Nickel Asia 등", country: "필리핀", pct: null }], owners: "현지 + 일본 투자" },
  { id: "nickel-r-canada", commodity: "니켈", type: "광물", metric: "reserve", site: "서드베리·보이에이", country: "캐나다", region: "온타리오", lat: 46.5, lng: -81.0, rank: 9, share: 3, amount: 2.2, unit: "백만 t", stakes: [{ holder: "Vale·Glencore", country: "브라질·스위스", pct: null }], owners: "다국적 광산기업" },
  { id: "nickel-r-china", commodity: "니켈", type: "광물", metric: "reserve", site: "진촨", country: "중국", region: "간쑤", lat: 38.5, lng: 102.2, rank: 8, share: 3, amount: 2.8, unit: "백만 t", stakes: [{ holder: "Jinchuan", country: "중국", pct: null }], owners: "국영 — 수입·해외 광산 의존" },
  { id: "nickel-r-usa", commodity: "니켈", type: "광물", metric: "reserve", site: "미네소타·미시간", country: "미국", region: "미네소타", lat: 47.5, lng: -92.0, rank: 10, share: 0.5, amount: 0.4, unit: "백만 t", stakes: [{ holder: "탐사·개발사", country: "미국", pct: null }], owners: "생산 미미, 전략광물 재개발 논의" },
  { id: "nickel-r-cuba", commodity: "니켈", type: "광물", metric: "reserve", site: "모아 벨트", country: "쿠바", region: "올긴", lat: 20.7, lng: -75.0, rank: 6, share: 4, amount: 5.5, unit: "백만 t", stakes: [{ holder: "국영·Sherritt", country: "쿠바·캐나다", pct: null }], owners: "국영 + 외국 합작" },
);

// ---- 희토류 매장 ----
COMMODITIES.push(
  { id: "ree-r-china", commodity: "희토류", type: "광물", metric: "reserve", site: "바이윈어보·남부 이온흡착", country: "중국", region: "네이멍구·장시", lat: 41.8, lng: 109.9, rank: 1, share: 37, amount: 44, unit: "백만 t REO", stakes: [{ holder: "China Northern RE 등", country: "중국", pct: null }], owners: "국영 지배 — 매장·생산·정련 모두 독점에 가까움" },
  { id: "ree-r-vietnam", commodity: "희토류", type: "광물", metric: "reserve", site: "라이쩌우·옌바이", country: "베트남", region: "북서부", lat: 22.3, lng: 103.5, rank: 6, share: 4, amount: 3.5, unit: "백만 t REO", stakes: [{ holder: "국영·합작", country: "베트남", pct: null }], owners: "매장 6위(USGS 2025 대폭 하향)이나 생산은 제한적 — 미·일 협력 개발 추진" },
  { id: "ree-r-brazil", commodity: "희토류", type: "광물", metric: "reserve", site: "아마파·고이아스", country: "브라질", region: "아마파·고이아스", lat: 0.9, lng: -52.0, rank: 2, share: 17, amount: 21, unit: "백만 t REO", stakes: [{ holder: "개발사·사모", country: "브라질·미국·영국", pct: null }], owners: "매장 상위·생산 초기 단계" },
  { id: "ree-r-russia", commodity: "희토류", type: "광물", metric: "reserve", site: "로보제로·토므토르", country: "러시아", region: "무르만스크·야쿠티야", lat: 67.9, lng: 34.9, rank: 3, share: 10, amount: 10, unit: "백만 t REO", stakes: [{ holder: "국영계열", country: "러시아", pct: null }], owners: "국영·준국영 — 개발 지연" },
  { id: "ree-r-india", commodity: "희토류", type: "광물", metric: "reserve", site: "케랄라·오디샤 모나자이트", country: "인도", region: "케랄라", lat: 8.5, lng: 76.9, rank: 4, share: 6, amount: 6.9, unit: "백만 t REO", stakes: [{ holder: "IREL", country: "인도", pct: null }], owners: "국영 IREL 독점" },
  { id: "ree-r-australia", commodity: "희토류", type: "광물", metric: "reserve", site: "마운트웰드", country: "호주", region: "웨스턴오스트레일리아", lat: -28.86, lng: 122.55, rank: 5, share: 4, amount: 5.7, unit: "백만 t REO", stakes: [{ holder: "Lynas", country: "호주", pct: 100 }], owners: "기관투자자 — 중국 외 주요 생산·매장" },
  { id: "ree-r-usa", commodity: "희토류", type: "광물", metric: "reserve", site: "마운틴패스", country: "미국", region: "캘리포니아", lat: 35.48, lng: -115.53, rank: 7, share: 1.5, amount: 1.8, unit: "백만 t REO", stakes: [{ holder: "MP Materials", country: "미국", pct: 100 }], owners: "미국 상장 — 생산 재개, 매장 비중은 작음" },
  { id: "ree-r-greenland", commodity: "희토류", type: "광물", metric: "reserve", site: "크바네피엘드·탄브리즈", country: "그린란드(덴마크)", region: "남부·동부", lat: 60.9, lng: -45.9, rank: 8, share: 1.5, amount: 1.5, unit: "백만 t REO", stakes: [{ holder: "탐사·개발사", country: "호주·캐나다 등", pct: null }], owners: "미개발 대형 자원 — 환경·정치 이슈" },
  { id: "ree-r-tanzania", commodity: "희토류", type: "광물", metric: "reserve", site: "응앙가", country: "탄자니아", region: "남부", lat: -10.0, lng: 36.0, rank: 9, share: 1, amount: 0.9, unit: "백만 t REO", stakes: [{ holder: "Peak Rare Earths 등", country: "호주", pct: null }], owners: "개발 단계" },
  { id: "ree-r-canada", commodity: "희토류", type: "광물", metric: "reserve", site: "토르·스트레인지레이크", country: "캐나다", region: "NWT·퀘벡", lat: 62.0, lng: -112.0, rank: 10, share: 1, amount: 0.8, unit: "백만 t REO", stakes: [{ holder: "탐사·개발사", country: "캐나다", pct: null }], owners: "미개발 매장 다수" },
);

// ---- 보크사이트 매장 ----
COMMODITIES.push(
  { id: "bauxite-r-guinea", commodity: "보크사이트", type: "광물", metric: "reserve", site: "보케·상가레디 벨트", country: "기니", region: "보케", lat: 11.0, lng: -14.3, rank: 1, share: 24, amount: 74, unit: "억 t", stakes: [{ holder: "CBG·중국·에미레이트 계", country: "다국적·기니", pct: null }], owners: "세계 최대 보크사이트 매장 — 정치 리스크 상존" },
  { id: "bauxite-r-australia", commodity: "보크사이트", type: "광물", metric: "reserve", site: "웨이파·고브", country: "호주", region: "퀸즐랜드·NT", lat: -12.65, lng: 141.87, rank: 2, share: 17, amount: 53, unit: "억 t", stakes: [{ holder: "Rio Tinto 등", country: "호주·영국", pct: null }], owners: "다국적 광산기업 — 생산·매장 모두 상위" },
  { id: "bauxite-r-vietnam", commodity: "보크사이트", type: "광물", metric: "reserve", site: "중부 고원 보크사이트", country: "베트남", region: "닥농·잘라이", lat: 12.0, lng: 107.7, rank: 3, share: 12, amount: 58, unit: "억 t", stakes: [{ holder: "국영·합작", country: "베트남", pct: null }], owners: "매장 상위, 생산은 제한적" },
  { id: "bauxite-r-brazil", commodity: "보크사이트", type: "광물", metric: "reserve", site: "트롬베타스 벨트", country: "브라질", region: "파라", lat: -1.5, lng: -56.4, rank: 4, share: 8, amount: 27, unit: "억 t", stakes: [{ holder: "MRN·Alcoa 등", country: "브라질·미국", pct: null }], owners: "현지·다국적 합작" },
  { id: "bauxite-r-jamaica", commodity: "보크사이트", type: "광물", metric: "reserve", site: "중부 보크사이트 구릉", country: "자메이카", region: "맨체스터 등", lat: 18.1, lng: -77.5, rank: 5, share: 6, amount: 20, unit: "억 t", stakes: [{ holder: "외국 알루미나사", country: "미국·중국·러시아", pct: null }], owners: "외국 자본 + 국영 지분" },
  { id: "bauxite-r-indonesia", commodity: "보크사이트", type: "광물", metric: "reserve", site: "빈탄·칼리만탄", country: "인도네시아", region: "리아우제도", lat: 0.9, lng: 104.5, rank: 6, share: 4, amount: 12, unit: "억 t", stakes: [{ holder: "Antam 등", country: "인도네시아", pct: null }], owners: "국영 + 원석 수출 규제" },
  { id: "bauxite-r-china", commodity: "보크사이트", type: "광물", metric: "reserve", site: "산시·구이저우", country: "중국", region: "산시성", lat: 37.5, lng: 112.0, rank: 7, share: 3.5, amount: 7, unit: "억 t", stakes: [{ holder: "Chinalco 등", country: "중국", pct: null }], owners: "국영 — 저품위·수입 의존" },
  { id: "bauxite-r-india", commodity: "보크사이트", type: "광물", metric: "reserve", site: "오디샤·안드라", country: "인도", region: "오디샤", lat: 20.9, lng: 83.2, rank: 8, share: 3, amount: 6.6, unit: "억 t", stakes: [{ holder: "NALCO 등", country: "인도", pct: null }], owners: "국영기업 지배" },
  { id: "bauxite-r-saudi", commodity: "보크사이트", type: "광물", metric: "reserve", site: "알바이타", country: "사우디아라비아", region: "카심", lat: 27.56, lng: 43.68, rank: 10, share: 1.5, amount: 1.8, unit: "억 t", stakes: [{ holder: "Ma'aden", country: "사우디", pct: 100 }], owners: "국영 마덴 — 수직계열 알루미나·알루미늄" },
  { id: "bauxite-r-russia", commodity: "보크사이트", type: "광물", metric: "reserve", site: "북우랄·코미", country: "러시아", region: "스베르들롭스크", lat: 60.2, lng: 60.0, rank: 9, share: 1.5, amount: 4.8, unit: "억 t", stakes: [{ holder: "Rusal", country: "러시아", pct: null }], owners: "러시아 과두자본 — 수입 보크사이트 의존도 높음" },
);

// ---- 백금족 매장 ----
COMMODITIES.push(
  { id: "pgm-r-southafrica", commodity: "백금족", type: "광물", metric: "reserve", site: "부시벨드 복합체", country: "남아프리카공화국", region: "림포포·노스웨스트", lat: -24.5, lng: 28.5, rank: 1, share: 88, amount: 63000, unit: "t", stakes: [{ holder: "Anglo American Platinum·Impala 등", country: "남아공·영국", pct: null }], owners: "세계 매장의 대부분 — 전력·노조 리스크" },
  { id: "pgm-r-russia", commodity: "백금족", type: "광물", metric: "reserve", site: "노릴스크-탈나흐", country: "러시아", region: "크라스노야르스크", lat: 69.33, lng: 88.2, rank: 2, share: 7, amount: 3900, unit: "t", stakes: [{ holder: "Nornickel", country: "러시아", pct: null }], owners: "러시아 과두자본 — 팔라듐 강세" },
  { id: "pgm-r-zimbabwe", commodity: "백금족", type: "광물", metric: "reserve", site: "그레이트다이크", country: "짐바브웨", region: "마쇼날랜드", lat: -18.1, lng: 30.6, rank: 3, share: 2, amount: 1200, unit: "t", stakes: [{ holder: "Zimplats(Implats)", country: "남아공", pct: null }], owners: "남아공 자본 주도" },
  { id: "pgm-r-usa", commodity: "백금족", type: "광물", metric: "reserve", site: "스틸워터", country: "미국", region: "몬태나", lat: 45.4, lng: -109.9, rank: 4, share: 1, amount: 900, unit: "t", stakes: [{ holder: "Sibanye-Stillwater", country: "남아공", pct: 100 }], owners: "남아공 자본 소유" },
  { id: "pgm-r-canada", commodity: "백금족", type: "광물", metric: "reserve", site: "서드베리·락데질", country: "캐나다", region: "온타리오", lat: 46.5, lng: -81.0, rank: 5, share: 0.5, amount: 310, unit: "t", stakes: [{ holder: "Vale·Impala Canada", country: "브라질·남아공", pct: null }], owners: "니켈 부산물 + 전용 광산" },
  { id: "pgm-r-finland", commodity: "백금족", type: "광물", metric: "reserve", site: "케비차·수호이키", country: "핀란드", region: "라플란드", lat: 67.7, lng: 26.9, rank: 6, share: 0.3, amount: 50, unit: "t", stakes: [{ holder: "Boliden 등", country: "스웨덴", pct: null }], owners: "북유럽 자본" },
  { id: "pgm-r-china", commodity: "백금족", type: "광물", metric: "reserve", site: "진촨 부산물", country: "중국", region: "간쑤", lat: 38.5, lng: 102.2, rank: 7, share: 0.2, amount: 30, unit: "t", stakes: [{ holder: "Jinchuan", country: "중국", pct: null }], owners: "국영 — 수요 대비 자급 미미" },
  { id: "pgm-r-colombia", commodity: "백금족", type: "광물", metric: "reserve", site: "초코 사금지", country: "콜롬비아", region: "초코", lat: 5.3, lng: -76.6, rank: 8, share: 0.2, amount: 20, unit: "t", stakes: [{ holder: "소규모 채굴", country: "콜롬비아", pct: null }], owners: "소규모·비공식 비중" },
  { id: "pgm-r-ethiopia", commodity: "백금족", type: "광물", metric: "reserve", site: "이우브도 벨트", country: "에티오피아", region: "남부", lat: 5.5, lng: 37.5, rank: 9, share: 0.1, amount: 10, unit: "t", stakes: [{ holder: "탐사 단계", country: "에티오피아", pct: null }], owners: "미개발" },
  { id: "pgm-r-serbia", commodity: "백금족", type: "광물", metric: "reserve", site: "보르 구리 부산물", country: "세르비아", region: "보르", lat: 44.08, lng: 22.1, rank: 10, share: 0.1, amount: 10, unit: "t", stakes: [{ holder: "Zijin", country: "중국", pct: null }], owners: "중국 쯔진 — 부산물 회수" },
);

// ---- 원유 매장 ----
COMMODITIES.push(
  { id: "oil-r-venezuela", commodity: "원유", type: "에너지", metric: "reserve", site: "오리노코 중질유 벨트", country: "베네수엘라", region: "오리노코", lat: 8.5, lng: -63.5, rank: 1, share: 18, amount: 3030, unit: "억 bbl", stakes: [{ holder: "PDVSA", country: "베네수엘라", pct: null }], owners: "국영 PDVSA — 매장 1위, 생산은 제재·설비로 저조" },
  { id: "oil-r-saudi", commodity: "원유", type: "에너지", metric: "reserve", site: "가와르(육상)·사파니야(해상)", country: "사우디아라비아", region: "동부주·페르시아만", lat: 25.4, lng: 49.6, rank: 2, share: 17, amount: 2670, unit: "억 bbl", stakes: [{ holder: "Saudi Aramco", country: "사우디", pct: null }], owners: "국영 아람코 — 매장·생산 모두 최상위 (대표 좌표: 가와르 육상)" },
  { id: "oil-r-iran", commodity: "원유", type: "에너지", metric: "reserve", site: "아바즈·아흐바즈 유전대", country: "이란", region: "후제스탄", lat: 31.3, lng: 48.7, rank: 3, share: 12, amount: 2090, unit: "억 bbl", stakes: [{ holder: "NIOC", country: "이란", pct: 100 }], owners: "국영 NIOC — 제재로 생산 억제" },
  { id: "oil-r-canada", commodity: "원유", type: "에너지", metric: "reserve", site: "앨버타 오일샌드", country: "캐나다", region: "앨버타", lat: 57.0, lng: -111.4, rank: 4, share: 10, amount: 1700, unit: "억 bbl", stakes: [{ holder: "Suncor·CNRL 등", country: "캐나다", pct: null }], owners: "오일샌드 매장 세계 상위 — 원가·환경 이슈" },
  { id: "oil-r-iraq", commodity: "원유", type: "에너지", metric: "reserve", site: "루마일라·키르쿠크", country: "이라크", region: "바스라·키르쿠크", lat: 30.5, lng: 47.5, rank: 5, share: 8, amount: 1450, unit: "억 bbl", stakes: [{ holder: "국영 + BP·CNPC 등", country: "이라크·외국", pct: null }], owners: "국영 주도 + 서비스계약" },
  { id: "oil-r-kuwait", commodity: "원유", type: "에너지", metric: "reserve", site: "부르간", country: "쿠웨이트", region: "남동부", lat: 29.03, lng: 47.95, rank: 7, share: 6, amount: 1010, unit: "억 bbl", stakes: [{ holder: "KPC/KOC", country: "쿠웨이트", pct: 100 }], owners: "국영 독점" },
  { id: "oil-r-uae", commodity: "원유", type: "에너지", metric: "reserve", site: "자쿰(해상)·바브(육상)", country: "아랍에미리트", region: "아부다비 해상(페르시아만)", lat: 24.88, lng: 53.65, rank: 6, share: 6, amount: 1110, unit: "억 bbl", stakes: [{ holder: "ADNOC", country: "UAE", pct: null }], owners: "국영 ADNOC — 대표 좌표: 어퍼자쿰 해상" },
  { id: "oil-r-russia", commodity: "원유", type: "에너지", metric: "reserve", site: "서시베리아 유전대", country: "러시아", region: "한티만시", lat: 61.0, lng: 70.0, rank: 8, share: 5, amount: 800, unit: "억 bbl", stakes: [{ holder: "Rosneft·Lukoil 등", country: "러시아", pct: null }], owners: "국영·준국영 지배" },
  { id: "oil-r-usa", commodity: "원유", type: "에너지", metric: "reserve", site: "퍼미언(육상)·멕시코만 대륙붕", country: "미국", region: "텍사스 육상 (걸프 해상 별도)", lat: 31.9, lng: -102.3, rank: 10, share: 3, amount: 450, unit: "억 bbl", stakes: [{ holder: "민간 메이저·셰일", country: "미국", pct: null }], owners: "생산 1위, 확인 매장은 중위 — 대표 좌표: 퍼미언 육상" },
  { id: "oil-r-libya", commodity: "원유", type: "에너지", metric: "reserve", site: "시르테 분지", country: "리비아", region: "시르테", lat: 29.0, lng: 18.0, rank: 9, share: 3, amount: 480, unit: "억 bbl", stakes: [{ holder: "NOC", country: "리비아", pct: null }], owners: "국영 — 정정 불안으로 생산 변동" },
);

// ---- 천연가스 매장 ----
COMMODITIES.push(
  { id: "gas-r-russia", commodity: "천연가스", type: "에너지", metric: "reserve", site: "야말·우렌고이·시베리아", country: "러시아", region: "야말로네네츠", lat: 66.0, lng: 76.6, rank: 1, share: 20, amount: 47.8, unit: "조 m³", stakes: [{ holder: "Gazprom·Novatek", country: "러시아", pct: null }], owners: "국영 중심 — 세계 최대 가스 매장" },
  { id: "gas-r-iran", commodity: "천연가스", type: "에너지", metric: "reserve", site: "사우스파스·노스파스", country: "이란", region: "페르시아만 해상(부셰르 남쪽)", lat: 26.55, lng: 52.15, rank: 2, share: 16, amount: 33.8, unit: "조 m³", stakes: [{ holder: "NIOC", country: "이란", pct: null }], owners: "국영 — 매장 2위, 수출 인프라·제재 제약" },
  { id: "gas-r-qatar", commodity: "천연가스", type: "에너지", metric: "reserve", site: "노스필드(사우스파스 북부)", country: "카타르", region: "페르시아만 해상(카타르 북동)", lat: 26.45, lng: 52.05, rank: 3, share: 12, amount: 23.8, unit: "조 m³", stakes: [{ holder: "QatarEnergy", country: "카타르", pct: null }], owners: "국영 — LNG 수출 강국" },
  { id: "gas-r-turkmenistan", commodity: "천연가스", type: "에너지", metric: "reserve", site: "갈키니시(요로탄)", country: "투르크메니스탄", region: "마리", lat: 37.6, lng: 61.8, rank: 4, share: 7, amount: 13.9, unit: "조 m³", stakes: [{ holder: "Türkmengaz", country: "투르크메니스탄", pct: null }], owners: "국영 — 중국 파이프라인 수출 중심" },
  { id: "gas-r-usa", commodity: "천연가스", type: "에너지", metric: "reserve", site: "애팔래치아·퍼미언 셰일", country: "미국", region: "펜실베이니아·텍사스", lat: 40.0, lng: -80.0, rank: 5, share: 6, amount: 13.4, unit: "조 m³", stakes: [{ holder: "민간 셰일 생산사", country: "미국", pct: null }], owners: "생산 1위, 확인 매장은 중상위" },
  { id: "gas-r-saudi", commodity: "천연가스", type: "에너지", metric: "reserve", site: "자푸라·가와르 수반가스", country: "사우디아라비아", region: "동부주", lat: 25.1, lng: 49.7, rank: 6, share: 4, amount: 8.5, unit: "조 m³", stakes: [{ holder: "Aramco", country: "사우디", pct: 100 }], owners: "아람코 — 비전통·수반가스 확대" },
  { id: "gas-r-uae", commodity: "천연가스", type: "에너지", metric: "reserve", site: "아부다비 해상 가스전", country: "아랍에미리트", region: "페르시아만 해상(아부다비 북서)", lat: 25.05, lng: 53.55, rank: 7, share: 3.5, amount: 7.7, unit: "조 m³", stakes: [{ holder: "ADNOC", country: "UAE", pct: null }], owners: "국영 ADNOC — 해상 가스·콘덴세이트 중심" },
  { id: "gas-r-venezuela", commodity: "천연가스", type: "에너지", metric: "reserve", site: "플라타포르마 델타나·동부 해상", country: "베네수엘라", region: "카리브해 해상(오리노코 삼각주 앞)", lat: 10.15, lng: -61.85, rank: 8, share: 3, amount: 5.5, unit: "조 m³", stakes: [{ holder: "PDVSA", country: "베네수엘라", pct: null }], owners: "국영 — 미개발 해상 매장 비중 큼" },
  { id: "gas-r-nigeria", commodity: "천연가스", type: "에너지", metric: "reserve", site: "니제르 델타·해상", country: "나이지리아", region: "기니만 해상·델타", lat: 4.35, lng: 6.85, rank: 9, share: 3, amount: 5.8, unit: "조 m³", stakes: [{ holder: "NNPC·Shell 등", country: "나이지리아·외국", pct: null }], owners: "국영 + IOC — 연안·해상 가스전" },
  { id: "gas-r-algeria", commodity: "천연가스", type: "에너지", metric: "reserve", site: "하시 르멜·사하라", country: "알제리", region: "사하라 북부", lat: 32.9, lng: 3.3, rank: 10, share: 2.5, amount: 4.5, unit: "조 m³", stakes: [{ holder: "Sonatrach", country: "알제리", pct: null }], owners: "국영 — 유럽 공급 대안" },
);

// ---- 석탄 매장 ----
COMMODITIES.push(
  { id: "coal-r-usa", commodity: "석탄", type: "에너지", metric: "reserve", site: "파우더리버·애팔래치아", country: "미국", region: "와이오밍·동부", lat: 44.0, lng: -105.4, rank: 1, share: 22, amount: 2490, unit: "억 t", stakes: [{ holder: "Peabody·Core Natural Resources 등", country: "미국", pct: null }], owners: "세계 최대 석탄 매장 — 생산은 중위" },
  { id: "coal-r-russia", commodity: "석탄", type: "에너지", metric: "reserve", site: "쿠즈바스·칸스크아친스크", country: "러시아", region: "케메로보", lat: 54.0, lng: 87.0, rank: 2, share: 15, amount: 1620, unit: "억 t", stakes: [{ holder: "SUEK 등", country: "러시아", pct: null }], owners: "러시아 과두·국영 혼재" },
  { id: "coal-r-australia", commodity: "석탄", type: "에너지", metric: "reserve", site: "보엔·시드니 분지", country: "호주", region: "퀸즐랜드·NSW", lat: -22.5, lng: 148.0, rank: 3, share: 14, amount: 1500, unit: "억 t", stakes: [{ holder: "BHP·Glencore 등", country: "호주·스위스", pct: null }], owners: "수출용 원료탄·발전탄" },
  { id: "coal-r-china", commodity: "석탄", type: "에너지", metric: "reserve", site: "산시·네이멍구·산시(섬서)", country: "중국", region: "산시성", lat: 38.0, lng: 112.5, rank: 4, share: 13, amount: 1430, unit: "억 t", stakes: [{ holder: "China Energy 등", country: "중국", pct: null }], owners: "국영 — 생산 1위, 매장 4위권" },
  { id: "coal-r-india", commodity: "석탄", type: "에너지", metric: "reserve", site: "자르칸드·오디샤·치하티스가르", country: "인도", region: "자르칸드", lat: 23.8, lng: 86.4, rank: 5, share: 10, amount: 1110, unit: "억 t", stakes: [{ holder: "Coal India", country: "인도", pct: null }], owners: "국영 Coal India 독점에 가까움" },
  { id: "coal-r-germany", commodity: "석탄", type: "에너지", metric: "reserve", site: "라인란트 갈탄·루르", country: "독일", region: "NRW", lat: 51.1, lng: 6.5, rank: 6, share: 4, amount: 360, unit: "억 t", stakes: [{ holder: "RWE 등", country: "독일", pct: null }], owners: "갈탄 매장 — 탈석탄 일정" },
  { id: "coal-r-ukraine", commodity: "석탄", type: "에너지", metric: "reserve", site: "돈바스", country: "우크라이나", region: "도네츠크·루한스크", lat: 48.0, lng: 38.0, rank: 8, share: 3.5, amount: 340, unit: "억 t", stakes: [{ holder: "국영·민간", country: "우크라이나", pct: null }], owners: "전쟁·점령 지역 이슈" },
  { id: "coal-r-kazakhstan", commodity: "석탄", type: "에너지", metric: "reserve", site: "에키바스투스·카라간다", country: "카자흐스탄", region: "파블로다르", lat: 51.7, lng: 75.3, rank: 10, share: 3, amount: 256, unit: "억 t", stakes: [{ holder: "Bogatyr 등", country: "카자흐스탄", pct: null }], owners: "국영·현지 자본" },
  { id: "coal-r-indonesia", commodity: "석탄", type: "에너지", metric: "reserve", site: "칼리만탄·수마트라", country: "인도네시아", region: "동칼리만탄", lat: -1.5, lng: 115.0, rank: 7, share: 3, amount: 349, unit: "억 t", stakes: [{ holder: "Adaro·Bumi 등", country: "인도네시아", pct: null }], owners: "현지 대기업 — 생산 상위·매장 중위" },
  { id: "coal-r-poland", commodity: "석탄", type: "에너지", metric: "reserve", site: "어퍼실레시아 탄전", country: "폴란드", region: "실레시아", lat: 50.26, lng: 19.02, rank: 9, share: 2.5, amount: 284, unit: "억 t", stakes: [{ holder: "국영·민간", country: "폴란드", pct: null }], owners: "확인매장 세계 9위 — 남아공(약 99억 t)은 톱10 밖" },
);

// ---- 우라늄 매장 ----
COMMODITIES.push(
  { id: "uranium-r-australia", commodity: "우라늄", type: "에너지", metric: "reserve", site: "올림픽댐·포마일", country: "호주", region: "사우스오스트레일리아", lat: -30.44, lng: 136.88, rank: 1, share: 28, amount: 1670, unit: "천 t U", stakes: [{ holder: "BHP 등", country: "호주", pct: null }], owners: "세계 최대 우라늄 매장 — 생산은 정책·가격에 따라 가변" },
  { id: "uranium-r-kazakhstan", commodity: "우라늄", type: "에너지", metric: "reserve", site: "남부 ISR 벨트", country: "카자흐스탄", region: "투르키스탄", lat: 45.5, lng: 67.0, rank: 2, share: 13, amount: 815, unit: "천 t U", stakes: [{ holder: "Kazatomprom", country: "카자흐스탄", pct: null }], owners: "국영 — 생산 1위, 매장 2위" },
  { id: "uranium-r-canada", commodity: "우라늄", type: "에너지", metric: "reserve", site: "애사바스카 분지", country: "캐나다", region: "서스캐처원", lat: 58.1, lng: -104.5, rank: 3, share: 10, amount: 588, unit: "천 t U", stakes: [{ holder: "Cameco·Orano", country: "캐나다·프랑스", pct: null }], owners: "고품위 매장 — 다국적 합작" },
  { id: "uranium-r-russia", commodity: "우라늄", type: "에너지", metric: "reserve", site: "자바이칼·야쿠티야", country: "러시아", region: "자바이칼", lat: 50.3, lng: 118.3, rank: 4, share: 8, amount: 486, unit: "천 t U", stakes: [{ holder: "ARMZ(Rosatom)", country: "러시아", pct: null }], owners: "국영 로사톰 계열" },
  { id: "uranium-r-namibia", commodity: "우라늄", type: "에너지", metric: "reserve", site: "로싱·후사브", country: "나미비아", region: "에롱고", lat: -22.5, lng: 15.0, rank: 5, share: 6, amount: 470, unit: "천 t U", stakes: [{ holder: "CNNC/CNUC(로싱)·CGN 주도 컨소시엄(후사브)·Epangelo", country: "중국·나미비아", pct: null }], owners: "중국 자본 비중 확대" },
  { id: "uranium-r-southafrica", commodity: "우라늄", type: "에너지", metric: "reserve", site: "비트바테르스란드 부산물", country: "남아프리카공화국", region: "하우텡", lat: -26.2, lng: 28.0, rank: 6, share: 5, amount: 320, unit: "천 t U", stakes: [{ holder: "금광 부산물·국영", country: "남아공", pct: null }], owners: "금 채굴 부산물 비중" },
  { id: "uranium-r-brazil", commodity: "우라늄", type: "에너지", metric: "reserve", site: "세아라·바이아", country: "브라질", region: "세아라", lat: -5.0, lng: -40.0, rank: 7, share: 4, amount: 310, unit: "천 t U", stakes: [{ holder: "INB(국영)", country: "브라질", pct: null }], owners: "국영 — 자국 원전용" },
  { id: "uranium-r-niger", commodity: "우라늄", type: "에너지", metric: "reserve", site: "아를리트·이무라렌", country: "니제르", region: "아가데즈", lat: 18.7, lng: 7.4, rank: 8, share: 4, amount: 280, unit: "천 t U", stakes: [{ holder: "니제르 국영(SOMAÏR 국유화, 2025.6)", country: "니제르", pct: null }], owners: "구 Orano 지분(63.4%) 국유화 — ICSID 중재 계류, 프랑스 영향 축소" },
  { id: "uranium-r-china", commodity: "우라늄", type: "에너지", metric: "reserve", site: "신장·내몽골", country: "중국", region: "신장", lat: 41.0, lng: 86.0, rank: 9, share: 3, amount: 220, unit: "천 t U", stakes: [{ holder: "CNNC", country: "중국", pct: null }], owners: "국영 — 해외 매장 확보 병행" },
  { id: "uranium-r-mongolia", commodity: "우라늄", type: "에너지", metric: "reserve", site: "도르노드·주운바얀", country: "몽골", region: "동부·남고비", lat: 47.5, lng: 114.0, rank: 10, share: 2, amount: 140, unit: "천 t U", stakes: [{ holder: "국영·합작(Orano 등)", country: "몽골·프랑스", pct: null }], owners: "개발 초기·지정학 민감" },
);
