/* ============================================================
   반도체 공급망 (원자재 분류 "반도체" — COMMODITIES 확장)
   ------------------------------------------------------------
   목적: 어느 국가·기업이 각 단계를 쥐고 있고, 어디서 전쟁·봉쇄가
   나면 공급망이 끊기는지 보기 위함. share = 세계 점유율 근사(%).
   ⚠️ 공개 자료 기반 근사치 — 시점·정의 따라 변동.
   ============================================================ */

const SEMI_SUPPLY = [
  // ---- 파운드리 (위탁생산) ----
  { id: "fdy-tsmc", commodity: "파운드리", type: "반도체", site: "TSMC 신주·타이난", country: "대만", region: "신주과학단지", lat: 24.77, lng: 121.0, rank: 1, share: 70,
    stakes: [{ holder: "대만 국가발전기금", country: "대만", pct: 6.4 }, { holder: "외국인 기관(ADR)", country: "미국 등", pct: 70 }],
    owners: "2025년 파운드리 점유율 ~70% — 첨단칩(≤5nm)의 ~90%가 대만 한 곳. 대만 유사시 세계 IT 정지. '실리콘 방패'" },
  { id: "fdy-samsung", commodity: "파운드리", type: "반도체", site: "삼성 파운드리 평택·화성", country: "대한민국", region: "경기", lat: 37.1, lng: 127.03, rank: 2, share: 7,
    stakes: [{ holder: "이재용 일가·특수관계인", country: "대한민국", pct: 20 }, { holder: "국민연금", country: "대한민국", pct: 7 }],
    owners: "TSMC의 유일한 선단공정 대항마" },
  { id: "fdy-smic", commodity: "파운드리", type: "반도체", site: "SMIC 상하이", country: "중국", region: "상하이", lat: 31.1, lng: 121.6, rank: 3, share: 6,
    stakes: [{ holder: "국유 대기금(빅펀드)", country: "중국", pct: null }],
    owners: "미 제재 속 DUV로 7nm — 중국 자립의 최전선" },
  { id: "fdy-umc", commodity: "파운드리", type: "반도체", site: "UMC 신주", country: "대만", region: "신주", lat: 24.78, lng: 120.99, rank: 4, share: 4,
    stakes: [{ holder: "대만·외국인 기관 분산", country: "—", pct: null }], owners: "성숙공정(28nm+) — 차량용 칩의 기둥" },
  { id: "fdy-gf", commodity: "파운드리", type: "반도체", site: "글로벌파운드리 몰타", country: "미국", region: "뉴욕", lat: 42.97, lng: -73.8, rank: 5, share: 4,
    stakes: [{ holder: "무바달라(UAE 국부펀드)", country: "UAE", pct: 73 }], owners: "미국 땅, 중동 소유 — 미 국방 칩 공급자" },
  { id: "fdy-huahong", commodity: "파운드리", type: "반도체", site: "화홍반도체 우시", country: "중국", region: "장쑤", lat: 31.6, lng: 120.3, rank: 6, share: 3,
    stakes: [{ holder: "국유 대기금", country: "중국", pct: null }], owners: "중국 2위 파운드리" },

  // ---- 메모리 ----
  { id: "mem-samsung", commodity: "메모리", type: "반도체", site: "삼성 평택 캠퍼스", country: "대한민국", region: "경기", lat: 37.0, lng: 127.05, rank: 2, share: 29,
    stakes: [{ holder: "이재용 일가·특수관계인", country: "대한민국", pct: 20 }, { holder: "외국인 기관", country: "—", pct: 50 }],
    owners: "세계 최대 반도체 캠퍼스 — 2025년 HBM 열세로 메모리 매출 1위를 SK에 내줌" },
  { id: "mem-skhynix", commodity: "메모리", type: "반도체", site: "SK하이닉스 이천", country: "대한민국", region: "경기", lat: 37.27, lng: 127.44, rank: 1, share: 30,
    stakes: [{ holder: "SK스퀘어", country: "대한민국", pct: 20 }, { holder: "국민연금", country: "대한민국", pct: 8 }],
    owners: "2025년 사상 첫 메모리 매출 세계 1위 — HBM 점유 ~57~60%, 엔비디아의 젖줄" },
  { id: "mem-micron", commodity: "메모리", type: "반도체", site: "마이크론 보이시", country: "미국", region: "아이다호", lat: 43.6, lng: -116.2, rank: 3, share: 20,
    stakes: [{ holder: "뱅가드·블랙록 등 기관", country: "미국", pct: null }], owners: "미국 유일의 메모리 대기업" },
  { id: "mem-kioxia", commodity: "메모리", type: "반도체", site: "키옥시아 요카이치", country: "일본", region: "미에", lat: 34.97, lng: 136.62, rank: 4, share: 9,
    stakes: [{ holder: "도시바", country: "일본", pct: 15.1 }, { holder: "SK하이닉스 관련 SPV", country: "대한민국", pct: 14 }],
    owners: "세계 최대급 NAND 단지 — 2024 상장, 베인은 2026년 완전 매각. 도시바 지분도 장내 매도로 지속 축소 중(2026.7 기준 약 15.1%)" },
  { id: "mem-ymtc", commodity: "메모리", type: "반도체", site: "YMTC 우한", country: "중국", region: "후베이", lat: 30.5, lng: 114.4, rank: 5, share: 4,
    stakes: [{ holder: "국유 대기금·후베이성", country: "중국", pct: null }], owners: "중국 NAND 자립 — 미 수출통제 대상" },
  { id: "mem-cxmt", commodity: "메모리", type: "반도체", site: "CXMT 허페이", country: "중국", region: "안후이", lat: 31.85, lng: 117.25, rank: 6, share: 3,
    stakes: [{ holder: "국유 대기금·안후이성", country: "중국", pct: null }], owners: "중국 DRAM 주자 — HBM 추격 중" },

  // ---- 노광장비 (Litho) ----
  { id: "litho-asml", commodity: "노광장비(Litho)", type: "반도체", site: "ASML 벨트호벤 본사공장", country: "네덜란드", region: "노르트브라반트", lat: 51.42, lng: 5.4, rank: 1, share: 85,
    stakes: [{ holder: "미국계 펀드 등 외국인 기관", country: "미국 등", pct: null }],
    owners: "EUV·DUV 노광기 최종 조립 — EUV는 세계 유일 · [회사] EUV 노광기 세계 유일 — 공급망 전체의 단일 실패점(SPOF). 對中 수출은 미·네 정부가 통제" },
  { id: "litho-asml-2", commodity: "노광장비(Litho)", type: "반도체", site: "ASML 윌턴 공장", country: "미국", region: "코네티컷", lat: 41.2, lng: -73.44,
    owners: "레티클 스테이지·핸들러 등 모듈, 광학 가공 · [회사] EUV 노광기 세계 유일 — 공급망 전체의 단일 실패점(SPOF). 對中 수출은 미·네 정부가 통제" },
  { id: "litho-asml-3", commodity: "노광장비(Litho)", type: "반도체", site: "ASML 샌디에이고 Cymer 공장", country: "미국", region: "캘리포니아", lat: 32.72, lng: -117.16,
    owners: "EUV 드롭릿 제너레이터·DUV 광원 제조 · [회사] EUV 노광기 세계 유일 — 공급망 전체의 단일 실패점(SPOF). 對中 수출은 미·네 정부가 통제" },
  { id: "litho-asml-4", commodity: "노광장비(Litho)", type: "반도체", site: "ASML 베를린 광학공장", country: "독일", region: "베를린", lat: 52.52, lng: 13.4,
    owners: "광학부품 (구 Berliner Glas) · [회사] EUV 노광기 세계 유일 — 공급망 전체의 단일 실패점(SPOF). 對中 수출은 미·네 정부가 통제" },
  { id: "litho-canon", commodity: "노광장비(Litho)", type: "반도체", site: "캐논 우쓰노미야 사업소", country: "일본", region: "도치기", lat: 36.56, lng: 139.88, rank: 2, share: 8,
    stakes: [{ holder: "일본 기관·개인 분산", country: "일본", pct: null }],
    owners: "노광장비 주력 생산 — 2025.9 신공장 가동, 생산능력 1.5배 · [회사] 나노임프린트로 EUV 우회 도전" },
  { id: "litho-canon-2", commodity: "노광장비(Litho)", type: "반도체", site: "캐논 아미 사업소", country: "일본", region: "이바라키", lat: 36.03, lng: 140.21,
    owners: "노광장비 부품가공·조립 · [회사] 나노임프린트로 EUV 우회 도전" },
  { id: "litho-nikon", commodity: "노광장비(Litho)", type: "반도체", site: "니콘 구마가야 제작소", country: "일본", region: "사이타마", lat: 36.15, lng: 139.39, rank: 3, share: 6,
    stakes: [{ holder: "일본 기관 분산", country: "일본", pct: null }],
    owners: "반도체 노광장비 개발·제조 일관 거점 (도쿄는 본사만) — 요코하마는 2025년 폐쇄 · [회사] DUV 잔존 강자" },
  { id: "litho-nikon-2", commodity: "노광장비(Litho)", type: "반도체", site: "니콘 사가미하라 제작소", country: "일본", region: "가나가와", lat: 35.55, lng: 139.35,
    owners: "노광용 합성석영유리·광학유리 소재 · [회사] DUV 잔존 강자" },

  // ---- 에칭·증착장비 ----
  { id: "etch-amat", commodity: "에칭·증착장비", type: "반도체", site: "AMAT 오스틴 공장", country: "미국", region: "텍사스", lat: 30.27, lng: -97.74, rank: 1, share: 22,
    stakes: [{ holder: "미국 기관 분산", country: "미국", pct: null }],
    owners: "주력 장비 생산기지 (1992~), 최근 대규모 증설 · [회사] 장비 종합 1위 — 증착 최강" },
  { id: "etch-amat-2", commodity: "에칭·증착장비", type: "반도체", site: "AMAT 싱가포르 탐피네스 공장", country: "싱가포르", region: "탐피네스", lat: 1.35, lng: 103.94,
    owners: "제2 대량생산 거점, 클린룸 2배 확장 · [회사] 장비 종합 1위 — 증착 최강" },
  { id: "etch-amat-3", commodity: "에칭·증착장비", type: "반도체", site: "AMAT 산타클라라 본사", country: "미국", region: "캘리포니아", lat: 37.39, lng: -121.97,
    owners: "본사·R&D 겸 일부 장비 제조 · [회사] 장비 종합 1위 — 증착 최강" },
  { id: "etch-lam", commodity: "에칭·증착장비", type: "반도체", site: "램리서치 바투카완 공장 (페낭)", country: "말레이시아", region: "페낭", lat: 5.28, lng: 100.44, rank: 2, share: 15,
    stakes: [{ holder: "미국 기관 분산", country: "미국", pct: null }],
    owners: "램 최대 제조시설 (2021~, 80만ft²+) · [회사] 에칭 1위 — 메모리 공정 필수" },
  { id: "etch-lam-2", commodity: "에칭·증착장비", type: "반도체", site: "램리서치 툴라틴 공장", country: "미국", region: "오리건", lat: 45.38, lng: -122.76,
    owners: "주력 생산, 2025년에도 증설 · [회사] 에칭 1위 — 메모리 공정 필수" },
  { id: "etch-lam-3", commodity: "에칭·증착장비", type: "반도체", site: "램리서치 프리몬트·리버모어 공장", country: "미국", region: "캘리포니아", lat: 37.55, lng: -121.99,
    owners: "본사 인접 제조·조립 · [회사] 에칭 1위 — 메모리 공정 필수" },
  { id: "etch-lam-4", commodity: "에칭·증착장비", type: "반도체", site: "램리서치 용인·화성 공장", country: "대한민국", region: "경기", lat: 37.24, lng: 127.18,
    owners: "Lam Korea — 식각·증착 모듈 조립 · [회사] 에칭 1위 — 메모리 공정 필수" },
  { id: "etch-tel", commodity: "에칭·증착장비", type: "반도체", site: "TEL 미야기 공장", country: "일본", region: "미야기", lat: 38.44, lng: 140.89, rank: 3, share: 15,
    stakes: [{ holder: "일본·외국인 기관", country: "일본", pct: null }],
    owners: "플라즈마 식각장비 — TEL 최대 매출 제품군 (도쿄는 본사만) · [회사] PR 도포(코터) 점유 ~90% — 숨은 독점" },
  { id: "etch-tel-2", commodity: "에칭·증착장비", type: "반도체", site: "TEL 야마나시 니라사키 공장", country: "일본", region: "야마나시", lat: 35.71, lng: 138.45,
    owners: "열처리·매엽 성막장비 · [회사] PR 도포(코터) 점유 ~90% — 숨은 독점" },
  { id: "etch-tel-3", commodity: "에칭·증착장비", type: "반도체", site: "TEL 구마모토 고시 공장", country: "일본", region: "구마모토", lat: 32.89, lng: 130.79,
    owners: "코터/디벨로퍼·세정·웨이퍼 본더 · [회사] PR 도포(코터) 점유 ~90% — 숨은 독점" },
  { id: "etch-tel-4", commodity: "에칭·증착장비", type: "반도체", site: "TEL 이와테 오슈 공장", country: "일본", region: "이와테", lat: 39.14, lng: 141.14,
    owners: "성막·열처리 — 생산능력 1.5배 증설 중 · [회사] PR 도포(코터) 점유 ~90% — 숨은 독점" },
  { id: "etch-naura", commodity: "에칭·증착장비", type: "반도체", site: "NAURA 베이징 이좡 산업화기지", country: "중국", region: "베이징", lat: 39.79, lng: 116.51, rank: 4, share: 4,
    stakes: [{ holder: "베이징시 국유자본", country: "중국", pct: null }],
    owners: "식각·PVD·CVD·세정장비 — 4기 확장 2024년 가동. 중국 최대 장비사 · [회사] 중국 최대 장비사 — 제재 속 내수로 급성장" },

  // ---- 검사·계측장비 ----
  { id: "insp-kla", commodity: "검사·계측장비", type: "반도체", site: "KLA 밀피타스 본사공장", country: "미국", region: "캘리포니아", lat: 37.43, lng: -121.9, rank: 1, share: 55,
    stakes: [{ holder: "미국 기관 분산", country: "미국", pct: null }],
    owners: "본사 겸 공장 — 웨이퍼 검사·계측 장비 · [회사] 웨이퍼 결함검사 과반 — 수율의 문지기" },
  { id: "insp-kla-2", commodity: "검사·계측장비", type: "반도체", site: "KLA 미그달 하에메크 공장", country: "이스라엘", region: "북부", lat: 32.68, lng: 35.24,
    owners: "검사장비 R&D·제조 허브 · [회사] 웨이퍼 결함검사 과반 — 수율의 문지기" },
  { id: "insp-kla-3", commodity: "검사·계측장비", type: "반도체", site: "KLA 싱가포르 공장", country: "싱가포르", region: "싱가포르", lat: 1.37, lng: 103.87,
    owners: "$2억 클린룸 제조동, 2026년까지 확장 · [회사] 웨이퍼 결함검사 과반 — 수율의 문지기" },
  { id: "insp-kla-4", commodity: "검사·계측장비", type: "반도체", site: "KLA 야브네 공장", country: "이스라엘", region: "중부", lat: 31.88, lng: 34.74,
    owners: "구 Orbotech — PCB·FPD 검사장비 · [회사] 웨이퍼 결함검사 과반 — 수율의 문지기" },
  { id: "insp-advantest", commodity: "검사·계측장비", type: "반도체", site: "어드반테스트 군마 공장 (오라마치)", country: "일본", region: "군마", lat: 36.25, lng: 139.46, rank: 2, share: 25,
    stakes: [{ holder: "일본·외국인 기관", country: "일본", pct: null }],
    owners: "반도체 테스터 유일 주력 공장 (도쿄는 본사만) · [회사] 칩 테스터 1위 — HBM 테스트 특수" },
  { id: "insp-advantest-2", commodity: "검사·계측장비", type: "반도체", site: "어드반테스트 Essai 프리몬트 공장", country: "미국", region: "캘리포니아", lat: 37.55, lng: -121.99,
    owners: "테스트 소켓 설계·제조 · [회사] 칩 테스터 1위 — HBM 테스트 특수" },
  { id: "insp-advantest-3", commodity: "검사·계측장비", type: "반도체", site: "어드반테스트 Altanova 공장 (뉴저지)", country: "미국", region: "뉴저지", lat: 40.58, lng: -74.41,
    owners: "테스트 인터페이스 보드 · [회사] 칩 테스터 1위 — HBM 테스트 특수" },
  { id: "insp-teradyne", commodity: "검사·계측장비", type: "반도체", site: "테라다인 페낭 생산거점", country: "말레이시아", region: "페낭", lat: 5.3, lng: 100.28, rank: 3, share: 15,
    stakes: [{ holder: "미국 기관 분산", country: "미국", pct: null }],
    owners: "테스터 주력 조립 — 중국 쑤저우 물량 이전 (노스리딩은 본사·개발) · [회사] 테스터 2위" },
  { id: "insp-teradyne-2", commodity: "검사·계측장비", type: "반도체", site: "테라다인 세부 공장", country: "필리핀", region: "세부", lat: 10.31, lng: 123.98,
    owners: "미국 외 최대 — 보드 제조·시험 · [회사] 테스터 2위" },

  // ---- 포토레지스트 (PR) ----
  { id: "pr-tok", commodity: "포토레지스트(PR)", type: "반도체", site: "TOK 고리야마 공장", country: "일본", region: "후쿠시마", lat: 37.4, lng: 140.36, rank: 1, share: 25,
    stakes: [{ holder: "일본 기관 분산", country: "일본", pct: null }],
    owners: "KrF·ArF 레지스트 주력 (가와사키는 본사) · [회사] EUV PR 강자 — 일본 합산 ~85%의 한 축" },
  { id: "pr-tok-2", commodity: "포토레지스트(PR)", type: "반도체", site: "TOK 고텐바 공장", country: "일본", region: "시즈오카", lat: 35.31, lng: 138.93,
    owners: "레지스트·막형성 도포액 · [회사] EUV PR 강자 — 일본 합산 ~85%의 한 축" },
  { id: "pr-tok-3", commodity: "포토레지스트(PR)", type: "반도체", site: "TOK 우쓰노미야 공장", country: "일본", region: "도치기", lat: 36.55, lng: 139.88,
    owners: "반도체·디스플레이 레지스트 · [회사] EUV PR 강자 — 일본 합산 ~85%의 한 축" },
  { id: "pr-tok-4", commodity: "포토레지스트(PR)", type: "반도체", site: "TOK 인천 송도 공장", country: "대한민국", region: "인천", lat: 37.38, lng: 126.66,
    owners: "삼성물산 JV — 2020년부터 EUV 레지스트 · [회사] EUV PR 강자 — 일본 합산 ~85%의 한 축" },
  { id: "pr-jsr", commodity: "포토레지스트(PR)", type: "반도체", site: "JSR 욧카이치 공장", country: "일본", region: "미에", lat: 34.97, lng: 136.62, rank: 2, share: 24,
    stakes: [{ holder: "JIC(일본 정부계 펀드)", country: "일본", pct: 100 }],
    owners: "ArF·EUV 포토레지스트 주력+개발 (도쿄는 본사만) · [회사] 2024년 일본 정부계가 통째로 인수 — PR의 '국가전략 자산화'" },
  { id: "pr-jsr-2", commodity: "포토레지스트(PR)", type: "반도체", site: "JSR 사가 공장 (JSR큐슈)", country: "일본", region: "사가", lat: 33.3, lng: 130.32,
    owners: "국내 제2공장 — 레지스트·디스플레이 재료 · [회사] 2024년 일본 정부계가 통째로 인수 — PR의 '국가전략 자산화'" },
  { id: "pr-jsr-3", commodity: "포토레지스트(PR)", type: "반도체", site: "JSR 루뱅 공장 (벨기에)", country: "벨기에", region: "플란데런", lat: 50.88, lng: 4.7,
    owners: "imec 합작 EUV 레지스트 양산 · [회사] 2024년 일본 정부계가 통째로 인수 — PR의 '국가전략 자산화'" },
  { id: "pr-jsr-4", commodity: "포토레지스트(PR)", type: "반도체", site: "JSR 서니베일 공장", country: "미국", region: "캘리포니아", lat: 37.39, lng: -122.03,
    owners: "미국 반도체 재료 생산 · [회사] 2024년 일본 정부계가 통째로 인수 — PR의 '국가전략 자산화'" },
  { id: "pr-shinetsu", commodity: "포토레지스트(PR)", type: "반도체", site: "신에츠 나오에쓰 공장", country: "일본", region: "니가타", lat: 37.18, lng: 138.24, rank: 3, share: 18,
    stakes: [{ holder: "일본·외국인 기관", country: "일본", pct: null }],
    owners: "KrF·ArF·EUV 레지스트 제1거점 (도쿄는 본사만) · [회사] 화학 소재 전방위 강자" },
  { id: "pr-shinetsu-2", commodity: "포토레지스트(PR)", type: "반도체", site: "신에츠 다케후 공장", country: "일본", region: "후쿠이", lat: 35.9, lng: 136.17,
    owners: "레지스트 제2거점 + 마스크 블랭크 · [회사] 화학 소재 전방위 강자" },
  { id: "pr-shinetsu-3", commodity: "포토레지스트(PR)", type: "반도체", site: "신에츠 윈린 공장", country: "대만", region: "윈린", lat: 23.71, lng: 120.54,
    owners: "해외 레지스트 거점 (2019~) · [회사] 화학 소재 전방위 강자" },
  { id: "pr-sumitomo", commodity: "포토레지스트(PR)", type: "반도체", site: "스미토모 오사카 공장", country: "일본", region: "오사카", lat: 34.68, lng: 135.44, rank: 4, share: 12,
    stakes: [{ holder: "스미토모 그룹", country: "일본", pct: null }],
    owners: "EUV·ArF 이머전 레지스트 핵심, 증설 중 · [회사] 2019 對韓 수출규제 3품목의 주역국 — 한국의 급소로 드러난 분야" },
  { id: "pr-sumitomo-2", commodity: "포토레지스트(PR)", type: "반도체", site: "스미토모 익산 공장 (동우화인켐)", country: "대한민국", region: "전북", lat: 35.94, lng: 126.95,
    owners: "자회사 — ArF 이머전 레지스트 (2024~) · [회사] 2019 對韓 수출규제 3품목의 주역국 — 한국의 급소로 드러난 분야" },
  { id: "pr-dupont", commodity: "포토레지스트(PR)", type: "반도체", site: "Qnity(구 듀폰) 사사카미 공장", country: "일본", region: "니가타", lat: 37.83, lng: 139.23, rank: 5, share: 10,
    stakes: [{ holder: "미국 기관 분산", country: "미국", pct: null }],
    owners: "레지스트 주력 — 2024년 증설로 능력 2배 (본사는 미 델라웨어) · [회사] 2025.11 듀폰서 분사한 Qnity Electronics 소속 — 비일본계 대안, 한국에 EUV PR 공장 투자" },
  { id: "pr-dupont-2", commodity: "포토레지스트(PR)", type: "반도체", site: "Qnity(구 듀폰) 천안 공장", country: "대한민국", region: "충남", lat: 36.82, lng: 127.16,
    owners: "EUV 레지스트 라인 (2021 완공) · [회사] 2025.11 듀폰서 분사한 Qnity Electronics 소속 — 비일본계 대안, 한국에 EUV PR 공장 투자" },

  // ---- 포토마스크 ----
  { id: "mask-toppan", commodity: "포토마스크", type: "반도체", site: "토판 아사카 공장", country: "일본", region: "사이타마", lat: 35.79, lng: 139.56, rank: 1, share: 30,
    stakes: [{ holder: "일본 기관 분산", country: "일본", pct: null }],
    owners: "최첨단 2nm급 마스크+R&D (도쿄는 본사만) · [회사] 외판 마스크 1위" },
  { id: "mask-toppan-2", commodity: "포토마스크", type: "반도체", site: "토판 시가 공장", country: "일본", region: "시가", lat: 35.11, lng: 136.2,
    owners: "마스크 양산 · [회사] 외판 마스크 1위" },
  { id: "mask-toppan-3", commodity: "포토마스크", type: "반도체", site: "토판 라운드록 공장", country: "미국", region: "텍사스", lat: 30.51, lng: -97.68,
    owners: "미국 마스크 — 2025년 40% 증설 · [회사] 외판 마스크 1위" },
  { id: "mask-toppan-4", commodity: "포토마스크", type: "반도체", site: "토판 상하이 공장", country: "중국", region: "상하이", lat: 31.19, lng: 121.44,
    owners: "중국 시장용 마스크 · [회사] 외판 마스크 1위" },
  { id: "mask-dnp", commodity: "포토마스크", type: "반도체", site: "DNP 카미후쿠오카 공장", country: "일본", region: "사이타마", lat: 35.88, lng: 139.52, rank: 2, share: 25,
    stakes: [{ holder: "일본 기관 분산", country: "일본", pct: null }],
    owners: "최첨단 마스크·2nm 개발 (도쿄는 본사만) · [회사] 인쇄기술의 반도체 전환" },
  { id: "mask-dnp-2", commodity: "포토마스크", type: "반도체", site: "DNP 가와사키 DTF 공장", country: "일본", region: "가나가와", lat: 35.55, lng: 139.69,
    owners: "키옥시아 합작 — 메모리용 마스크 · [회사] 인쇄기술의 반도체 전환" },
  { id: "mask-photronics", commodity: "포토마스크", type: "반도체", site: "포트로닉스 브룩필드 본사공장", country: "미국", region: "코네티컷", lat: 41.48, lng: -73.41, rank: 3, share: 15,
    stakes: [{ holder: "미국 기관 분산", country: "미국", pct: null }],
    owners: "본사 겸 IC 마스크 생산 · [회사] 미국 유일 대형 마스크 전업사" },
  { id: "mask-photronics-2", commodity: "포토마스크", type: "반도체", site: "포트로닉스 신주 공장 (PDMC)", country: "대만", region: "신주", lat: 24.78, lng: 121.0,
    owners: "DNP 합작 첨단 마스크 — 아시아 핵심 · [회사] 미국 유일 대형 마스크 전업사" },
  { id: "mask-photronics-3", commodity: "포토마스크", type: "반도체", site: "포트로닉스 천안 공장 (PKL)", country: "대한민국", region: "충남", lat: 36.82, lng: 127.15,
    owners: "IC·FPD 마스크 · [회사] 미국 유일 대형 마스크 전업사" },
  { id: "mask-photronics-4", commodity: "포토마스크", type: "반도체", site: "포트로닉스 샤먼 공장", country: "중국", region: "푸젠", lat: 24.48, lng: 118.09,
    owners: "DNP 합작 IC 마스크 (2019~) · [회사] 미국 유일 대형 마스크 전업사" },
  { id: "mask-hoya", commodity: "포토마스크", type: "반도체", site: "HOYA 나가사카 공장", country: "일본", region: "야마나시", lat: 35.83, lng: 138.39, rank: 4, share: 12,
    stakes: [{ holder: "일본·외국인 기관", country: "일본", pct: null }],
    owners: "EUV 마스크 블랭크 핵심 (도쿄는 본사만) — 사실상 독점 · [회사] EUV 마스크 블랭크는 사실상 독점 — 또 하나의 SPOF" },
  { id: "mask-hoya-2", commodity: "포토마스크", type: "반도체", site: "HOYA 하치오지 공장", country: "일본", region: "도쿄", lat: 35.69, lng: 139.29,
    owners: "마스크·블랭크 생산 · [회사] EUV 마스크 블랭크는 사실상 독점 — 또 하나의 SPOF" },
  { id: "mask-hoya-3", commodity: "포토마스크", type: "반도체", site: "HOYA 싱가포르 공장", country: "싱가포르", region: "싱가포르", lat: 1.35, lng: 103.82,
    owners: "블랭크 — EUV 라인 증설 중 · [회사] EUV 마스크 블랭크는 사실상 독점 — 또 하나의 SPOF" },

  // ---- 웨이퍼·잉곳 ----
  { id: "wafer-shinetsu", commodity: "웨이퍼·잉곳", type: "반도체", site: "신에츠 시라카와 공장", country: "일본", region: "후쿠시마", lat: 37.14, lng: 140.15, rank: 1, share: 30,
    stakes: [{ holder: "일본·외국인 기관", country: "일본", pct: null }],
    owners: "세계 300mm 웨이퍼 ~20% 담당 주력 · [회사] 실리콘 웨이퍼 1위 — 일본 합산 ~55%" },
  { id: "wafer-shinetsu-2", commodity: "웨이퍼·잉곳", type: "반도체", site: "신에츠 이소베 공장", country: "일본", region: "군마", lat: 36.32, lng: 138.92,
    owners: "SEH 발상지 — 실리콘 결정·웨이퍼 · [회사] 실리콘 웨이퍼 1위 — 일본 합산 ~55%" },
  { id: "wafer-shinetsu-3", commodity: "웨이퍼·잉곳", type: "반도체", site: "신에츠 샤알람 공장 (말레이시아)", country: "말레이시아", region: "슬랑오르", lat: 3.07, lng: 101.52,
    owners: "세계 최대급 단일 웨이퍼 가공장 · [회사] 실리콘 웨이퍼 1위 — 일본 합산 ~55%" },
  { id: "wafer-sumco", commodity: "웨이퍼·잉곳", type: "반도체", site: "SUMCO 이마리 공장", country: "일본", region: "사가", lat: 33.26, lng: 129.88, rank: 2, share: 25,
    stakes: [{ holder: "일본 기관 분산", country: "일본", pct: null }],
    owners: "300mm 웨이퍼 집약 주력 · [회사] 웨이퍼 2위" },
  { id: "wafer-sumco-2", commodity: "웨이퍼·잉곳", type: "반도체", site: "SUMCO 요네자와 공장", country: "일본", region: "야마가타", lat: 37.92, lng: 140.12,
    owners: "300mm 잉곳 성장·폴리시드 · [회사] 웨이퍼 2위" },
  { id: "wafer-sumco-3", commodity: "웨이퍼·잉곳", type: "반도체", site: "SUMCO 오무라 공장", country: "일본", region: "나가사키", lat: 32.92, lng: 129.96,
    owners: "잉곳·소구경 — 300mm는 2026년 이마리로 통합 · [회사] 웨이퍼 2위" },
  { id: "wafer-sumco-4", commodity: "웨이퍼·잉곳", type: "반도체", site: "SUMCO 윈린 공장 (FST)", country: "대만", region: "윈린", lat: 23.79, lng: 120.25,
    owners: "대만 합작 200/300mm 웨이퍼 · [회사] 웨이퍼 2위" },
  { id: "wafer-gw", commodity: "웨이퍼·잉곳", type: "반도체", site: "글로벌웨이퍼스 신주 본사공장", country: "대만", region: "신주", lat: 24.81, lng: 120.99, rank: 3, share: 17,
    stakes: [{ holder: "대만 기관 분산", country: "대만", pct: null }],
    owners: "본사 겸 12인치 웨이퍼 생산 · [회사] 대만 소재 자립의 축 — 미국·유럽 증설" },
  { id: "wafer-gw-2", commodity: "웨이퍼·잉곳", type: "반도체", site: "글로벌웨이퍼스 셔먼 공장", country: "미국", region: "텍사스", lat: 33.64, lng: -96.61,
    owners: "신규 300mm — 2024년 말 첫 출하 · [회사] 대만 소재 자립의 축 — 미국·유럽 증설" },
  { id: "wafer-gw-3", commodity: "웨이퍼·잉곳", type: "반도체", site: "글로벌웨이퍼스 노바라 공장 (MEMC)", country: "이탈리아", region: "피에몬테", lat: 45.45, lng: 8.62,
    owners: "유럽 웨이퍼·에피택셜 · [회사] 대만 소재 자립의 축 — 미국·유럽 증설" },
  { id: "wafer-gw-4", commodity: "웨이퍼·잉곳", type: "반도체", site: "글로벌웨이퍼스 프레데릭스순 공장", country: "덴마크", region: "셸란", lat: 55.84, lng: 12.07,
    owners: "초고순도 FZ 실리콘 · [회사] 대만 소재 자립의 축 — 미국·유럽 증설" },
  { id: "wafer-siltronic", commodity: "웨이퍼·잉곳", type: "반도체", site: "실트로닉 부르크하우젠 공장", country: "독일", region: "바이에른", lat: 48.17, lng: 12.83, rank: 4, share: 12,
    stakes: [{ holder: "바커케미(독일)", country: "독일", pct: 31 }],
    owners: "단결정+300mm 전통 주력 (뮌헨은 본사만) · [회사] 유럽 유일 대형 웨이퍼사" },
  { id: "wafer-siltronic-2", commodity: "웨이퍼·잉곳", type: "반도체", site: "실트로닉 프라이베르크 공장", country: "독일", region: "작센", lat: 50.92, lng: 13.34,
    owners: "300mm 양산 전용 · [회사] 유럽 유일 대형 웨이퍼사" },
  { id: "wafer-siltronic-3", commodity: "웨이퍼·잉곳", type: "반도체", site: "실트로닉 싱가포르 공장", country: "싱가포르", region: "싱가포르", lat: 1.35, lng: 103.94,
    owners: "신규 300mm 팹 2024년 개소 · [회사] 유럽 유일 대형 웨이퍼사" },
  { id: "wafer-siltronic-4", commodity: "웨이퍼·잉곳", type: "반도체", site: "실트로닉 포틀랜드 공장", country: "미국", region: "오리건", lat: 45.53, lng: -122.7,
    owners: "200mm 웨이퍼 · [회사] 유럽 유일 대형 웨이퍼사" },
  { id: "wafer-sksiltron", commodity: "웨이퍼·잉곳", type: "반도체", site: "SK실트론 구미 공장", country: "대한민국", region: "경북", lat: 36.11, lng: 128.34, rank: 5, share: 11,
    stakes: [{ holder: "SK(주)", country: "대한민국", pct: 51 }, { holder: "최태원 회장 (TRS)", country: "대한민국", pct: 29 }],
    owners: "300mm 포함 실리콘 웨이퍼 주력 — SK가 경영권 매각 추진(2025~) · [회사] 한국 유일 웨이퍼사 — SK가 경영권 매각 추진 중(2025~)" },
  { id: "wafer-sksiltron-2", commodity: "웨이퍼·잉곳", type: "반도체", site: "SK실트론 어번 공장 (미시간)", country: "미국", region: "미시간", lat: 43.6, lng: -84.07,
    owners: "SiC 웨이퍼 (구 듀폰 사업) · [회사] 한국 유일 웨이퍼사 — SK가 경영권 매각 추진 중(2025~)" },
  { id: "wafer-sksiltron-3", commodity: "웨이퍼·잉곳", type: "반도체", site: "SK실트론 베이시티 공장 (미시간)", country: "미국", region: "미시간", lat: 43.59, lng: -83.89,
    owners: "SiC 웨이퍼 신공장 (2022~) · [회사] 한국 유일 웨이퍼사 — SK가 경영권 매각 추진 중(2025~)" },

  // ---- 특수가스·소재 ----
  { id: "gas-neon", commodity: "특수가스·소재", type: "반도체", site: "네온 (잉가스·크라이오인)", country: "우크라이나", region: "오데사·마리우폴", lat: 46.48, lng: 30.72, rank: 1, share: 50,
    stakes: [{ holder: "Ingas·Cryoin", country: "우크라이나", pct: null }],
    owners: "노광 레이저용 네온 — 전쟁 전 세계의 절반 공급. 2022년 침공으로 생산 중단(잉가스 마리우폴 공장은 러시아군 점령) 후 잉가스는 비점령지 이전, 크라이오인(오데사)도 조업 재개했으나 전쟁 전 물량은 미회복 — 중국이 최대 공급국으로 부상. '전쟁→반도체' 리스크의 실증 사례" },
  { id: "gas-hf", commodity: "특수가스·소재", type: "반도체", site: "고순도 불화수소 (스텔라케미파)", country: "일본", region: "오사카", lat: 34.6, lng: 135.43, rank: 2, share: 70,
    stakes: [{ holder: "일본 기관 분산", country: "일본", pct: null }],
    owners: "초고순도(12N) 에칭가스 과점 — 2019 對韓 수출규제 품목" },
  { id: "gas-helium", commodity: "특수가스·소재", type: "반도체", site: "헬륨 (아마릴로 헬륨권)", country: "미국", region: "텍사스", lat: 35.22, lng: -101.83, rank: 3, share: 40,
    stakes: [{ holder: "Messer(독일계 가스회사, 민간 100%)", country: "독일", pct: null }], owners: "냉각·퍼지용 — 카타르와 양분. 미 BLM은 연방 헬륨 시스템(비축분·클리프사이드 필드·파이프라인)을 2024.6 Messer에 매각 완료(약 4.23억 달러)" },
  { id: "gas-palladium", commodity: "특수가스·소재", type: "반도체", site: "팔라듐 (노릴스크)", country: "러시아", region: "시베리아", lat: 69.35, lng: 88.2, rank: 4, share: 40,
    stakes: [{ holder: "노르니켈", country: "러시아", pct: null }], owners: "도금·센서용 — 제재에도 대체 불가라 예외 거래" },

  // ---- 후공정 (OSAT·패키징) ----
  { id: "osat-ase", commodity: "후공정(OSAT)", type: "반도체", site: "ASE 가오슝", country: "대만", region: "가오슝", lat: 22.62, lng: 120.3, rank: 1, share: 28,
    stakes: [{ holder: "대만·외국인 기관", country: "대만", pct: null }], owners: "패키징·테스트 1위 — 여기도 대만" },
  { id: "osat-cowos", commodity: "후공정(OSAT)", type: "반도체", site: "TSMC CoWoS 주난", country: "대만", region: "먀오리", lat: 24.7, lng: 120.88, rank: 2, share: 20,
    stakes: [{ holder: "TSMC", country: "대만", pct: 100 }],
    owners: "AI칩·HBM 첨단 패키징의 병목 — 엔비디아 공급량을 여기가 결정" },
  { id: "osat-amkor", commodity: "후공정(OSAT)", type: "반도체", site: "앰코 인천 송도 K5 공장", country: "대한민국", region: "인천", lat: 37.38, lng: 126.66, rank: 3, share: 14,
    stakes: [{ holder: "김주진 일가", country: "미국(한국계)", pct: null }],
    owners: "글로벌 R&D+첨단 패키징 허브 — 인텔 EMIB 수탁 · [회사] 베트남·미국 애리조나로 분산 확장" },
  { id: "osat-amkor-2", commodity: "후공정(OSAT)", type: "반도체", site: "앰코 문틴루파 공장", country: "필리핀", region: "메트로 마닐라", lat: 14.38, lng: 121.05,
    owners: "리드프레임 등 레거시 패키징 (1989~) · [회사] 베트남·미국 애리조나로 분산 확장" },
  { id: "osat-amkor-3", commodity: "후공정(OSAT)", type: "반도체", site: "앰코 박닌 공장", country: "베트남", region: "박닌", lat: 21.19, lng: 106.07,
    owners: "최대 캠퍼스 (2023~) — SiP·메모리 첨단 패키징 · [회사] 베트남·미국 애리조나로 분산 확장" },
  { id: "osat-amkor-4", commodity: "후공정(OSAT)", type: "반도체", site: "앰코 애리조나 피오리아 공장", country: "미국", region: "애리조나", lat: 33.58, lng: -112.24,
    owners: "미국 첨단 패키징 (2025~ 건설, TSMC 애리조나 연계) · [회사] 베트남·미국 애리조나로 분산 확장" },
  { id: "osat-jcet", commodity: "후공정(OSAT)", type: "반도체", site: "JCET 장인", country: "중국", region: "장쑤", lat: 31.91, lng: 120.26, rank: 4, share: 11,
    stakes: [{ holder: "국유 대기금 등", country: "중국", pct: null }], owners: "중국 최대 OSAT" },

  // ---- EDA·설계IP ----
  { id: "eda-synopsys", commodity: "EDA·설계IP", type: "반도체", site: "시놉시스 서니베일", country: "미국", region: "캘리포니아", lat: 37.37, lng: -122.04, rank: 1, share: 32,
    stakes: [{ holder: "미국 기관 분산", country: "미국", pct: null }], owners: "설계 소프트웨어 1위 — 對中 수출통제의 무기" },
  { id: "eda-cadence", commodity: "EDA·설계IP", type: "반도체", site: "케이던스 산호세", country: "미국", region: "캘리포니아", lat: 37.33, lng: -121.89, rank: 2, share: 30,
    stakes: [{ holder: "미국 기관 분산", country: "미국", pct: null }], owners: "미국 EDA 3사 합산 ~75%" },
  { id: "eda-siemens", commodity: "EDA·설계IP", type: "반도체", site: "지멘스 EDA 윌슨빌", country: "미국", region: "오리건", lat: 45.3, lng: -122.77, rank: 3, share: 13,
    stakes: [{ holder: "지멘스", country: "독일", pct: 100 }], owners: "구 멘토그래픽스 — 독일 소유, 미국 운영" },
  { id: "eda-arm", commodity: "EDA·설계IP", type: "반도체", site: "ARM 케임브리지", country: "영국", region: "케임브리지", lat: 52.2, lng: 0.13, rank: 4, share: 10,
    stakes: [{ holder: "소프트뱅크", country: "일본", pct: 88 }],
    owners: "모바일 칩 설계 IP의 표준 — 영국 소재·일본 소유·미국 상장" },

  // ---- 칩 설계 (팹리스 — GPU·CPU·AP 설계, 제조는 파운드리 위탁) ----
  // share = 상위 10대 팹리스 매출 대비 비중 (TrendForce 2026.4, 2025년 매출 기준)
  { id: "des-nvidia", commodity: "칩 설계(팹리스)", type: "반도체", site: "엔비디아 산타클라라", country: "미국", region: "캘리포니아", lat: 37.37, lng: -121.96, rank: 1, share: 57,
    stakes: [{ holder: "미국 기관 분산 (뱅가드·블랙록 등)", country: "미국", pct: null }],
    owners: "AI GPU ~90% 독점 — 설계는 미국, 생산은 TSMC, HBM은 한국. 3국 합작품" },
  { id: "des-broadcom", commodity: "칩 설계(팹리스)", type: "반도체", site: "브로드컴 팰로앨토", country: "미국", region: "캘리포니아", lat: 37.44, lng: -122.14, rank: 2, share: 11,
    stakes: [{ holder: "미국 기관 분산", country: "미국", pct: null }],
    owners: "네트워크·통신칩 + 빅테크 맞춤 AI칩(구글 TPU 등) 설계" },
  { id: "des-qualcomm", commodity: "칩 설계(팹리스)", type: "반도체", site: "퀄컴 샌디에이고", country: "미국", region: "캘리포니아", lat: 32.9, lng: -117.2, rank: 3, share: 11,
    stakes: [{ holder: "미국 기관 분산", country: "미국", pct: null }],
    owners: "모바일 AP·모뎀의 지배자 — 스마트폰 공급망의 시작점" },
  { id: "des-amd", commodity: "칩 설계(팹리스)", type: "반도체", site: "AMD 산타클라라", country: "미국", region: "캘리포니아", lat: 37.38, lng: -121.97, rank: 4, share: 10,
    stakes: [{ holder: "미국 기관 분산", country: "미국", pct: null }],
    owners: "CPU·GPU 양면 도전자 — 전량 TSMC 위탁" },
  { id: "des-mediatek", commodity: "칩 설계(팹리스)", type: "반도체", site: "미디어텍 신주", country: "대만", region: "신주", lat: 24.78, lng: 121.01, rank: 5, share: 5,
    stakes: [{ holder: "대만·외국인 기관", country: "대만", pct: null }],
    owners: "중저가 모바일 AP 1위 — 설계까지 대만인 이중 집중" },
  { id: "des-apple", commodity: "칩 설계(팹리스)", type: "반도체", site: "애플 실리콘 쿠퍼티노", country: "미국", region: "캘리포니아", lat: 37.33, lng: -122.01, rank: 6, share: 8,
    stakes: [{ holder: "미국 기관 분산", country: "미국", pct: null }],
    owners: "자사용 M·A칩 — TSMC 최신공정의 최대 단골(첫 물량 독점)" },
  { id: "des-hisilicon", commodity: "칩 설계(팹리스)", type: "반도체", site: "하이실리콘(화웨이) 선전", country: "중국", region: "광둥", lat: 22.65, lng: 113.88, rank: 7, share: 4,
    stakes: [{ holder: "화웨이 (종업원지주)", country: "중국", pct: 100 }],
    owners: "미 제재의 최대 표적 — SMIC 7nm 기린칩으로 부활 시도" },
];

// 원자재 데이터에 편입 (분류 "반도체")
// ⚠️ EXTRA_SCRIPTS(index.html)는 동적 스크립트를 async=false 없이 붙여 실행 순서가
//    비결정적이다. 이 파일(39KB)이 commodities.js(113KB)보다 먼저 실행되면 예전엔
//    `COMMODITIES` 미정의로 ReferenceError가 나 109개가 병합 안 돼 "반도체=마커 0"이었다.
//    → 로드 순서 무관하게: 지금 되면 즉시 병합, 아직이면 준비될 때까지 폴링해 1회만 병합.
(function mergeSemiSupplyIntoCommodities() {
  var merged = false;
  function tryMerge() {
    if (merged) return true;
    if (typeof COMMODITIES === "undefined" || !Array.isArray(COMMODITIES)) return false;
    COMMODITIES.push.apply(COMMODITIES, SEMI_SUPPLY);
    merged = true;
    return true;
  }
  if (tryMerge()) return;                 // commodities.js가 먼저 로드된 정상 경로
  var tries = 0;                          // 아니면 준비될 때까지 폴링(최대 ~10s)
  var iv = setInterval(function () {
    if (tryMerge() || ++tries > 200) clearInterval(iv);
  }, 50);
})();
