/* ============================================================
   기술·전략 제조 거점 (반도체·장비 제외)
   ------------------------------------------------------------
   category:
     system   — 시스템·브랜드 최종 제품 (EV·스마트폰 등)
     assembly — 전자 위탁 조립 (EMS, 폭스콘 등)
     battery  — 배터리 셀·팩
   segment: 자동차 | 핸드폰 | … (원자재 분류 2단 종목)
   status: 가동 | 건설 | 계획  ("건설"|"계획" → 점선 마커)
   products: 해당 거점 주요 생산품 (상세)
   ⚠️ 공개 자료 기반 큐레이션. 전 공장 전수 아님. 좌표·믹스 근사.
   ============================================================ */

const TECH_PLANTS = [

  // ========== 시스템·브랜드 ==========
  // ---- 테슬라 ----
  { id: "tesla-fremont", category: "system", segment: "자동차", company: "테슬라", name: "프리몬트 공장",
    country: "미국", lat: 37.492, lng: -121.944, status: "가동",
    products: "Model 3·Y 완성차 조립, 드라이브유닛·내장 일부 (Model S·X는 2026-05-09 최종 생산 후 단종)",
    note: "구 NUMMI. 테슬라 최초 완성차 공장. 구 S/X 라인 공간은 옵티머스(휴머노이드) 생산으로 전환 중." },
  { id: "tesla-giga-nv", category: "system", segment: "에너지", company: "테슬라", name: "기가 네바다",
    country: "미국", lat: 39.538, lng: -119.440, status: "가동",
    products: "4680 등 배터리 셀·모듈, Powerwall/메가팩 관련, 모터·세미 부품",
    note: "파나소닉 협업 셀 생산 병행. 초기 '기가팩토리' 상징. 완성차 최종 조립은 아님." },
  { id: "tesla-giga-ny", category: "system", segment: "에너지", company: "테슬라", name: "기가 뉴욕 (버팔로)",
    country: "미국", lat: 42.995, lng: -78.835, status: "가동",
    products: "태양광 모듈·Solar Roof 관련, 에너지 제품 부품",
    note: "솔라시티 계열. 완성차 주력 아님." },
  { id: "tesla-giga-sh", category: "system", segment: "자동차", company: "테슬라", name: "기가 상하이",
    country: "중국", lat: 30.875, lng: 121.785, status: "가동",
    products: "Model 3·Model Y 완성차 (중국 내수 + 유럽·아태 수출)",
    note: "해외 최초 기가. 링강. 단일 단지 생산량 세계 최상위권." },
  { id: "tesla-giga-berlin", category: "system", segment: "자동차", company: "테슬라", name: "기가 베를린-브란덴부르크",
    country: "독일", lat: 52.397, lng: 13.801, status: "가동",
    products: "Model Y 완성차 (유럽 사양), 배터리 셀 라인 확대 계획",
    note: "유럽 거점. 그륀하이데. 현지 공급망·규제 이슈 상존." },
  { id: "tesla-giga-tx", category: "system", segment: "자동차", company: "테슬라", name: "기가 텍사스",
    country: "미국", lat: 30.221, lng: -97.618, status: "가동",
    products: "Model Y 완성차, Cybertruck, 구조 배터리 팩·대형 주조",
    note: "글로벌 HQ 겸 공장. 오스틴. 차세대 생산 방식 실험 거점." },
  { id: "tesla-giga-mx", category: "system", segment: "자동차", company: "테슬라", name: "기가 멕시코 (몬테레이)",
    country: "멕시코", lat: 25.78, lng: -100.15, status: "계획(보류)",
    products: "차세대 저가·소형 차량 (계획, 모델 미확정)",
    note: "2023년 2월 발표 후 2024년 7월부터 무기한 보류(미국 관세·정책 불확실성). 재개 일정 미정." },

  // ---- BYD ----
  { id: "byd-shenzhen", category: "system", segment: "자동차", company: "BYD", name: "선전 본부·생산",
    country: "중국", lat: 22.65, lng: 114.05, status: "가동",
    products: "승용 EV·PHEV, 상용차 일부, 전장·전자 부품",
    note: "BYD 본거지. 배터리·차체 수직계열 상징." },
  { id: "byd-xian", category: "system", segment: "자동차", company: "BYD", name: "시안 공장",
    country: "중국", lat: 34.34, lng: 108.94, status: "가동",
    products: "승용 EV 대량 (한·당·송 등 시리즈 중심 물량)",
    note: "중국 내 핵심 완성차 거점. 수출 물량도 상당." },
  { id: "byd-changsha", category: "system", segment: "자동차", company: "BYD", name: "창사 공장",
    country: "중국", lat: 28.23, lng: 112.94, status: "가동",
    products: "승용 EV·PHEV 완성차",
    note: "후난 대형 생산 기지." },
  { id: "byd-hefei", category: "system", segment: "자동차", company: "BYD", name: "허페이 공장",
    country: "중국", lat: 31.82, lng: 117.23, status: "가동",
    products: "승용 EV 완성차",
    note: "안후이 EV 클러스터. 중국 내수·수출." },
  { id: "byd-brazil", category: "system", segment: "자동차", company: "BYD", name: "카마사리 (브라질)",
    country: "브라질", lat: -12.70, lng: -38.32, status: "가동",
    products: "승용 EV 현지 조립 (남미 시장)",
    note: "남미 생산·시장 교두보. 관세·현지화 대응." },
  { id: "byd-thailand", category: "system", segment: "자동차", company: "BYD", name: "라용 (태국)",
    country: "태국", lat: 12.68, lng: 101.28, status: "가동",
    products: "승용 EV 완성차 (아세안 내수·역내 수출)",
    note: "동남아 허브." },
  { id: "byd-hungary", category: "system", segment: "자동차", company: "BYD", name: "세게드 (헝가리)",
    country: "헝가리", lat: 46.25, lng: 20.15, status: "건설",
    products: "승용 EV 완성차 (유럽 사양, 건설 중)",
    note: "EU 시장 대응 공장. 건설·인허가 단계." },

  // ---- 삼성전자 (모바일 조립 — 반도체 팹 제외) ----
  { id: "samsung-gumi", category: "system", segment: "핸드폰", company: "삼성전자", name: "구미 사업장",
    country: "대한민국", lat: 36.12, lng: 128.38, status: "가동",
    products: "스마트폰·태블릿 일부, 네트워크 장비·모듈",
    note: "국내 모바일·네트워크 생산. 반도체 팹 아님." },
  { id: "samsung-vn-bacninh", category: "system", segment: "핸드폰", company: "삼성전자", name: "박닌·옌퐁 (베트남)",
    country: "베트남", lat: 21.18, lng: 106.07, status: "가동",
    products: "갤럭시 스마트폰 대량 조립, 무선 이어폰·웨어러블 일부",
    note: "삼성 글로벌 스마트폰 생산의 핵심 축." },
  { id: "samsung-vn-thainguyen", category: "system", segment: "핸드폰", company: "삼성전자", name: "타이응우옌 (베트남)",
    country: "베트남", lat: 21.59, lng: 105.84, status: "가동",
    products: "스마트폰 조립, 디스플레이·카메라 모듈 등 부품",
    note: "북부 베트남 삼성 클러스터." },
  { id: "samsung-india-noida", category: "system", segment: "핸드폰", company: "삼성전자", name: "노이다 (인도)",
    country: "인도", lat: 28.58, lng: 77.45, status: "가동",
    products: "갤럭시 스마트폰 (인도 내수·중저가·일부 수출)",
    note: "인도 내수·생산 거점. 중국 리스크 분산." },

  // ---- 애플 ----
  { id: "apple-austin", category: "system", segment: "컴퓨터", company: "애플", name: "오스틴 (맥 프로 등)",
    country: "미국", lat: 30.40, lng: -97.72, status: "가동",
    products: "Mac Pro 등 고가 데스크탑 제한 조립, 일부 서버·시제품",
    note: "미국 내 제한적 조립. 아이폰·맥북 대량은 EMS 위탁." },
  { id: "apple-cupertino", category: "system", segment: "설계", company: "애플", name: "애플 파크 (본사·설계)",
    country: "미국", lat: 37.33, lng: -122.01, status: "가동",
    products: "제품 설계·실리콘(칩 설계)·OS·공급망 기획 (양산 아님)",
    note: "제조 주도권은 설계·A/M 시리즈·공급망 통제. 양산은 조립 EMS 참고." },

  // ========== 조립 EMS ==========
  { id: "foxconn-longhua", category: "assembly", segment: "핸드폰", company: "폭스콘", name: "선전 롱화",
    country: "중국", lat: 22.655, lng: 114.025, status: "가동",
    products: "아이폰 조립(일부 세대), 전자 부품·모듈 SMT, 기타 브랜드 EMS",
    note: "폭스콘 시티. 애플 등 EMS 상징 거점." },
  { id: "foxconn-zhengzhou", category: "assembly", segment: "핸드폰", company: "폭스콘", name: "정저우 (아이폰 시티)",
    country: "중국", lat: 34.75, lng: 113.80, status: "가동",
    products: "아이폰 주력 최종 조립·테스트 (연 1억 대 안팎 — 세계 아이폰의 약 절반, 성수기 일 최대 약 50만 대)",
    note: "세계 최대급 아이폰 생산. 노동·봉쇄 시 글로벌 출하 직격." },
  { id: "foxconn-chengdu", category: "assembly", segment: "태블릿·전자", company: "폭스콘", name: "청두",
    country: "중국", lat: 30.57, lng: 104.07, status: "가동",
    products: "iPad 조립, 노트북·전자 제품 일부",
    note: "서부 내륙 생산 거점." },
  { id: "foxconn-taiyuan", category: "assembly", segment: "전자일반", company: "폭스콘", name: "타이위안",
    country: "중국", lat: 37.87, lng: 112.55, status: "가동",
    products: "스마트폰·전자 부품 조립, 금속 케이스 등 기구",
    note: "산시 대규모 EMS 캠퍼스." },
  { id: "foxconn-india-chennai", category: "assembly", segment: "핸드폰", company: "폭스콘", name: "첸나이·스리페룸부두르",
    country: "인도", lat: 12.97, lng: 79.95, status: "가동",
    products: "아이폰 최종 조립 (인도 생산 비중 확대 중)",
    note: "차이나 플러스 원. 인도 내수·수출." },
  { id: "foxconn-vietnam", category: "assembly", segment: "핸드폰", company: "폭스콘", name: "박장·박닌 (베트남)",
    country: "베트남", lat: 21.28, lng: 106.20, status: "가동",
    products: "아이폰·에어팟 등 애플 제품 조립, 기타 전자",
    note: "동남아 이전 축." },
  { id: "foxconn-mexico-juarez", category: "assembly", segment: "전자일반", company: "폭스콘", name: "시우다드후아레스",
    country: "멕시코", lat: 31.69, lng: -106.42, status: "가동",
    products: "휴대폰·셋톱·네트워킹 등 전자기기 조립",
    note: "북미 니어쇼어링. 미 국경 인접." },
  { id: "foxconn-czech", category: "assembly", segment: "PC·서버", company: "폭스콘", name: "파르두비체 등 (체코)",
    country: "체코", lat: 50.03, lng: 15.78, status: "가동",
    products: "PC·서버·데이터센터 장비 조립",
    note: "유럽 EMS·엔터프라이즈 IT 거점." },
  { id: "foxconn-wisconsin", category: "assembly", segment: "전자일반", company: "폭스콘", name: "마운트플레전트 (위스콘신)",
    country: "미국", lat: 42.71, lng: -87.91, status: "가동",
    products: "AI 데이터 서버 조립·통합, 데이터센터 인프라(네트워킹·쿨링·전력)",
    note: "당초 LCD 공약 대비 장기 축소 논란. 2025년 11월 5.69억 달러 추가 투자·1,374명 신규 고용 발표로 AI 서버 생산 거점으로 전환·확장 중." },
  { id: "pegatron-shanghai", category: "assembly", segment: "핸드폰", company: "럭스쉐어", name: "상하이·쿤산 (구 페가트론)",
    country: "중국", lat: 31.15, lng: 121.45, status: "가동",
    products: "아이폰 조립 (구 페가트론 라인), 통신·PC 보드 일부",
    note: "페가트론은 중국 아이폰 조립에서 사실상 철수. 쿤산 공장은 2023년 12월 럭스쉐어가 지분 62.5% 인수, 상하이 시설도 럭스쉐어 계열 리전정밀이 운영권 인수. 애플 주요 EMS는 현재 폭스콘·럭스쉐어." },
  { id: "wistron-india", category: "assembly", segment: "핸드폰", company: "타타 일렉트로닉스", name: "나라사푸라 (인도, 구 위스트론)",
    country: "인도", lat: 12.85, lng: 77.67, status: "가동",
    products: "아이폰 조립",
    note: "구 위스트론 공장. 2023년 타타가 지분 100% 인수, 위스트론 인도 아이폰 사업 철수." },

  // ========== 배터리 ==========
  { id: "catl-ningde", category: "battery", segment: "EV배터리", company: "CATL", name: "닝더 본부·공장",
    country: "중국", lat: 26.66, lng: 119.52, status: "가동",
    products: "LFP·NMC 등 리튬이온 셀·모듈·팩, ESS용 셀",
    note: "세계 1위 배터리 본거지. R&D·양산 중심." },
  { id: "catl-yibin", category: "battery", segment: "EV배터리", company: "CATL", name: "이빈",
    country: "중국", lat: 28.77, lng: 104.62, status: "가동",
    products: "EV용 리튬이온 셀 대량 생산",
    note: "사천 대형 기지. 수력 등 전력 이점." },
  { id: "catl-germany", category: "battery", segment: "EV배터리", company: "CATL", name: "아른슈타트 (독일)",
    country: "독일", lat: 50.84, lng: 10.95, status: "가동",
    products: "유럽 OEM향 EV 배터리 셀·모듈",
    note: "튀링겐. 유럽 현지 생산 교두보." },
  { id: "catl-hungary", category: "battery", segment: "EV배터리", company: "CATL", name: "데브레첸 (헝가리)",
    country: "헝가리", lat: 47.53, lng: 21.63, status: "건설",
    products: "EV용 셀·팩 (유럽 확대, 건설·램프업)",
    note: "유럽 초대형 투자. 일정 유동적." },

  { id: "lges-ochang", category: "battery", segment: "EV배터리", company: "LG에너지솔루션", name: "오창",
    country: "대한민국", lat: 36.72, lng: 127.43, status: "가동",
    products: "파우치·원통형 등 EV·IT용 셀, 모듈·팩",
    note: "국내 핵심 R&D·생산." },
  { id: "lges-nanjing", category: "battery", segment: "EV배터리", company: "LG에너지솔루션", name: "난징",
    country: "중국", lat: 32.06, lng: 118.80, status: "가동",
    products: "EV·ESS용 리튬이온 셀",
    note: "중국 생산. 미·중 공급망·IRA 규정과 연계된 전략 자산." },
  { id: "lges-poland", category: "battery", segment: "EV배터리", company: "LG에너지솔루션", name: "브로츠와프 (폴란드)",
    country: "폴란드", lat: 51.14, lng: 16.95, status: "가동",
    products: "유럽 OEM향 EV 배터리 셀·모듈 (파우치 중심)",
    note: "유럽 최대급 한국계 배터리 단지." },
  { id: "lges-michigan", category: "battery", segment: "EV배터리", company: "LG에너지솔루션", name: "홀랜드 (미시간)",
    country: "미국", lat: 42.79, lng: -86.11, status: "가동",
    products: "북미 OEM향 EV 배터리 셀·팩",
    note: "GM 등 협업. IRA 대응." },
  { id: "lges-arizona", category: "battery", segment: "ESS·기타", company: "LG에너지솔루션", name: "애리조나",
    country: "미국", lat: 33.25, lng: -111.63, status: "건설",
    products: "원통형 46시리즈 셀 중심 (2026년 상반기 양산 목표), ESS(LFP) 라인은 건설 보류",
    note: "애리조나 퀸크릭. 미국 확대. ESS용 LFP 라인은 2024년 6월 건설 중단(투자 시점 조정)." },

  // ---- 파나소닉 에너지 (일본 본진 + 북미 EV) ----
  { id: "panasonic-suminoe", category: "battery", segment: "EV배터리", company: "파나소닉", name: "스미노에 공장 (오사카)",
    country: "일본", lat: 34.615, lng: 135.475, status: "가동",
    products: "원통형 리튬이온 셀 (차량용 2170 등, 일본 양산 거점)",
    note: "파나소닉 에너지 일본 핵심. 북미와 이원 공급(듀얼 리전) 축의 본진." },
  { id: "panasonic-wakayama", category: "battery", segment: "EV배터리", company: "파나소닉", name: "와카야마 공장 (기노카와)",
    country: "일본", lat: 34.270, lng: 135.365, status: "가동",
    products: "차량용 원통형 리튬이온 셀",
    note: "파나소닉 공식 네트워크: 차량용 원통형 전지. 일본 내 주력 양산." },
  { id: "panasonic-kaizuka", category: "battery", segment: "EV배터리", company: "파나소닉", name: "가이즈카 (오사카)",
    country: "일본", lat: 34.430, lng: 135.360, status: "가동",
    products: "원통형 리튬이온 셀",
    note: "파나소닉 에너지 관련 법인·공장. 간사이 전지 클러스터." },
  { id: "panasonic-nevada", category: "battery", segment: "EV배터리", company: "파나소닉", name: "네바다 공장 (테슬라 기가 협업)",
    country: "미국", lat: 39.538, lng: -119.440, status: "가동",
    products: "원통형 셀 18650·2170 등 (테슬라 차량·에너지, 약 40GWh급)",
    note: "2017~ 가동. 테슬라 기가 네바다 내. 북미 1호 거점." },
  { id: "panasonic-kansas", category: "battery", segment: "EV배터리", company: "파나소닉", name: "캔자스 공장 (디소토)",
    country: "미국", lat: 38.98, lng: -94.97, status: "가동",
    products: "차량용 원통형 2170 셀 (북미 OEM·테슬라 등, 목표 ~32GWh)",
    note: "2025.7 공식 가동·양산 개시. 네바다에 이은 북미 2호. 향후 데이터센터용 전환 계획 보도 있음." },

  // ---- 삼성SDI (한국·유럽·동남아) ----
  { id: "sdi-ulsan", category: "battery", segment: "EV배터리", company: "삼성SDI", name: "울산",
    country: "대한민국", lat: 35.50, lng: 129.35, status: "가동",
    products: "각형·원통형 등 EV·IT용 배터리 셀",
    note: "국내 주력 생산." },
  { id: "sdi-cheonan", category: "battery", segment: "EV배터리", company: "삼성SDI", name: "천안",
    country: "대한민국", lat: 36.82, lng: 127.15, status: "가동",
    products: "소형·원통형·IT·모빌리티용 셀, EV 관련 라인",
    note: "국내 핵심 단지 중 하나. 연구·양산." },
  { id: "sdi-hungary", category: "battery", segment: "EV배터리", company: "삼성SDI", name: "괴드 (헝가리)",
    country: "헝가리", lat: 47.69, lng: 19.14, status: "가동",
    products: "유럽 OEM향 EV 배터리 셀·모듈",
    note: "유럽 거점. 헝가리 배터리 벨트." },
  { id: "sdi-malaysia", category: "battery", segment: "EV배터리", company: "삼성SDI", name: "세렘반 (말레이시아)",
    country: "말레이시아", lat: 2.72, lng: 101.94, status: "가동",
    products: "원통형·소형 리튬이온 셀 (IT·모빌리티·일부 車용)",
    note: "동남아 생산. 글로벌 소형·원통형 공급." },

  // ---- SK온 ----
  { id: "skon-seosan", category: "battery", segment: "EV배터리", company: "SK온", name: "서산",
    country: "대한민국", lat: 36.78, lng: 126.45, status: "가동",
    products: "파우치형 EV 배터리 셀·모듈",
    note: "국내 핵심. 현대차 그룹 등 공급." },
  { id: "skon-georgia", category: "battery", segment: "EV배터리", company: "SK온", name: "커머스 (조지아)",
    country: "미국", lat: 34.20, lng: -83.46, status: "가동",
    products: "북미 EV용 배터리 셀·팩 (현대·기아 등)",
    note: "IRA·완성차 동반 투자 축." },
  { id: "skon-hungary", category: "battery", segment: "EV배터리", company: "SK온", name: "코마롬 (헝가리)",
    country: "헝가리", lat: 47.74, lng: 18.12, status: "가동",
    products: "유럽 OEM향 파우치형 EV 셀·모듈",
    note: "유럽 생산. 헝가리 배터리 벨트." },

  // ---- BYD 배터리 (중국 다거점) ----
  { id: "byd-battery-shenzhen", category: "battery", segment: "EV배터리", company: "BYD", name: "선전·블레이드 배터리",
    country: "중국", lat: 22.70, lng: 114.20, status: "가동",
    products: "LFP 블레이드 배터리 셀·팩, 자사 차량용 + 외부 공급",
    note: "완성차 수직계열. 안전·원가 경쟁력 상징." },
  { id: "byd-battery-chongqing", category: "battery", segment: "EV배터리", company: "BYD", name: "충칭 배터리",
    country: "중국", lat: 29.56, lng: 106.55, status: "가동",
    products: "LFP 등 EV용 셀·팩 (자사 완성차·외부)",
    note: "서부 대형 전지·차 클러스터." },
  { id: "byd-battery-changsha", category: "battery", segment: "EV배터리", company: "BYD", name: "창사 배터리",
    country: "중국", lat: 28.20, lng: 113.00, status: "가동",
    products: "블레이드 등 LFP 셀·팩",
    note: "완성차 공장과 연계된 전지 생산." },

  // ---- CATL 추가 거점 ----
  { id: "catl-xining", category: "battery", segment: "EV배터리", company: "CATL", name: "시닝 (칭하이)",
    country: "중국", lat: 36.62, lng: 101.78, status: "가동",
    products: "리튬이온 셀 (서부 기지, 원재료·전력 이점)",
    note: "내륙·청정전력 활용 생산. 중국 서부 축." },
  { id: "catl-liyang", category: "battery", segment: "EV배터리", company: "CATL", name: "리양 (장쑤)",
    country: "중국", lat: 31.42, lng: 119.48, status: "가동",
    products: "EV·ESS용 셀·모듈",
    note: "장쑤 대형 기지. 동부 연안 공급." },
];

/* 2단 분류: category → segment (원자재 종목 드롭다운) */
const TECH_SEGMENTS_BY_CAT = {
  system:   ["자동차", "핸드폰", "컴퓨터", "설계", "에너지"],
  assembly: ["핸드폰", "태블릿·전자", "PC·서버", "전자일반"],
  battery:  ["EV배터리", "ESS·기타"],
};

const TECH_CAT_META = {
  system:   { label: "시스템·브랜드", color: "#5c9ded", emoji: "🚗" },
  assembly: { label: "조립 EMS",      color: "#e8b339", emoji: "🏭" },
  battery:  { label: "배터리",         color: "#69f0ae", emoji: "🔋" },
};
